tree 実績情報 = {
	クリアＡ　海から　　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／海" },
		説明 = "Clear A - From the Sea ★CP+1\nMain story route. You land in the Demon Realm from the sea and defeat the Demon Lord Kayblis.",
	},
	クリアＡ　空から　　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／空" },
		説明 = "Clear A - From the Sky ★CP+1\nMain story route. Toppos pulls Rance Castle and you charge into the enemy base, defeating Kayblis.",
	},
	クリアＡ　強行突破　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／強行" },
		説明 = "Clear A - Forced Breakthrough ★CP+1\nMain story route. You push through the Demon Realm with only the Fiend Slayers, repel several Demon Lords, and defeat Kayblis.",
	},
	クリアＡ　魔物界大侵攻　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／魔物界" },
		説明 = "Clear A - Great Demon Realm Invasion ★CP+1\nMain story route. After retaking all regions, humanity's full army invades the Demon Realm and you defeat Kayblis during the assault.",
	},
	クリアＢ　魔王を倒したが　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／魔王を倒したが" },
		説明 = "Clear B - Defeated the Demon Lord, but… ★CP+1\nIncomplete route. You defeat Demon Lord Kayblis, but…",
	},
	クリアＢ　タイムカプセル　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／タイムカプセル" },
		説明 = "Clear B - Time Capsule ★CP+1\nIncomplete route. You place the Demon Lord into a time capsule, but the demon army closes in…",
	},
	クリアＢ　地底大作戦　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／地底" },
		説明 = "Clear B - Underground Operation ★CP+1\nIncomplete route. You attempt to reach the enemy base through the underground, but time runs out and you confront Demon Lord Miki…",
	},
	クリアＢ　魔王美樹　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／魔王美樹" },
		説明 = "Clear B - Demon Lord Miki ★CP+1\nIncomplete route. You defeat Kayblis, but Miki awakens as the new Demon Lord…",
	},
	クリアＢ　神の真実　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／女神" },
		説明 = "Clear B - God's Truth ★CP+1\nIncomplete route. You challenge the gods, but due to insufficient preparation you are crushed by the Goddess.",
	},
	クリアＢ　異界の魔王　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／異界の魔王" },
		説明 = "Clear B - Demon Lord from Another World ★CP+1\nIncomplete route. Demon Lord Miki appears leading an army of Steel Horrors.",
	},
	クリアＣ　魔王ケイブリス　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／魔王ケイブリス" },
		説明 = "Clear C - Demon Lord Kayblis ★CP+1\nBad end. The world falls completely under Demon Lord Kayblis.",
	},
	クリアＣ　勇者の成就　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／勇者" },
		説明 = "Clear C - Hero's Fulfillment ★CP+1\nBad end. The Hero fulfills their destiny, but the world does not survive.",
	},
	クリアＣ　人類滅亡　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／人類滅亡" },
		説明 = "Clear C - Humanity's Extinction ★CP+1\nBad end. All major regions fall to the demon army and humanity is wiped out.",
	},
	クリアＣ　敗北　　　　　　　　　　　★ＣＰ＋１ = {
		種類 = 10,
		ボーナス = "ＣＰ＋１",
		値 = (list) { "ルート／本戦敗北" },
		説明 = "Clear C - Defeat ★CP+1\nBad end. Unfortunately, Rance's current party is not strong enough to win.",
	},
	"達成(クリア時)　初クリア　　　　　　★継続プレイ解放" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "ルート／初クリア" },
		説明 = "Achieved (on Clear) - First Clear ★Continue-Play Unlock\nFrom the next playthrough onward, CP bonuses become selectable.",
	},
	達成　？？解放条件全達成　　　　　　★２部解放 = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "ルート／第２部解放" },
		隠し表示 = 1,
		説明 = "Achievement - All ?? Conditions Completed ★Part 2 Unlock\nAll ?? unlock requirements are fulfilled, allowing Part 2 to begin.",
	},
	"達成(第２部クリア時)　全クリア" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "ルート／第２部クリア" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Complete Clear\nThis concludes the entire Rance series. Thank you for playing.",
	},
	達成　実績２０個　　　　　　　　　　★物理倍率＋１ = {
		種類 = 20,
		ボーナス = "物理倍率＋１",
		値 = 20,
		説明 = "Achievement - 20 Achievements ★Physical Multiplier +1\nObtain 20 or more achievements in total. Bonus: Permanent Physical Multiplier +1.",
	},
	達成　実績４０個　　　　　　　　　　★魔法倍率＋１ = {
		種類 = 20,
		ボーナス = "魔法倍率＋１",
		値 = 40,
		説明 = "Achievement - 40 Achievements ★Magic Multiplier +1\nObtain 40 or more achievements in total. Bonus: Permanent Magic Multiplier +1.",
	},
	達成　実績６０個　　　　　　　　　　★物理倍率＋１ = {
		種類 = 20,
		ボーナス = "物理倍率＋１",
		値 = 60,
		説明 = "Achievement - 60 Achievements ★Physical Multiplier +1\nObtain 60 or more achievements in total. Bonus: Permanent Physical Multiplier +1.",
	},
	達成　実績８０個　　　　　　　　　　★魔法倍率＋１ = {
		種類 = 20,
		ボーナス = "魔法倍率＋１",
		値 = 80,
		説明 = "Achievement - 80 Achievements ★Magic Multiplier +1\nObtain 80 or more achievements in total. Bonus: Permanent Magic Multiplier +1.",
	},
	達成　実績１００個　　　　　　　　　★物理倍率＋１ = {
		種類 = 20,
		ボーナス = "物理倍率＋１",
		値 = 100,
		説明 = "Achievement - 100 Achievements ★Physical Multiplier +1\nObtain 100 or more achievements in total. Bonus: Permanent Physical Multiplier +1.",
	},
	"達成(クリア時)　タイニリーチＥ　　　★レア確率ＵＰ" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／タイニリーチＥ" },
		説明 = "Achieved (on Clear) - Tiny Leech E ★Increased Rare Rate\nYou obtain the treasure Tiny Leech E. Bonus: Permanent increase to rare drop rate.",
	},
	"達成(クリア時)　マリアの可能性　　　●分岐発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／マリアと王子" },
		説明 = "Achieved (on Clear) - Maria's Possibility ●Branch Occurs\nThere is a possibility that Dark Rance and Maria become lovers.",
	},
	"達成(クリア時)　奈落の王　　　　　　●分岐発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／奈落の王" },
		説明 = "Achieved (on Clear) - King of the Abyss ●Branch Occurs\nThere is a possibility that the King of Heaven appears.",
	},
	"達成(クリア時)　海獣　　　　　　　　★物理倍率＋１" = {
		種類 = 10,
		ボーナス = "物理倍率＋１",
		値 = (list) { "達成／海獣" },
		説明 = "Achieved (on Clear) - Sea Beast ★Physical Multiplier +1\nYou defeat the Sea Beast raid boss. Bonus: Permanent Physical Multiplier +1.",
	},
	"達成(クリア時)　怪獣　　　　　　　　★物理倍率＋１" = {
		種類 = 10,
		ボーナス = "物理倍率＋１",
		値 = (list) { "達成／怪獣" },
		説明 = "Achieved (on Clear) - Kaiju ★Physical Multiplier +1\nYou defeat the Kaiju UR. Bonus: Permanent Physical Multiplier +1.",
	},
	"達成(クリア時)　リーザス魔人２撃破　★異常レジスト＋１" = {
		種類 = 10,
		ボーナス = "異常レジスト＋１",
		値 = (list) { "達成／リーザス魔人２" },
		説明 = "Achieved (on Clear) - Rizeas: Two Demon Lords Defeated ★Status Resist +1\nYou defeat two Demon Lords in the same turn while in Rizeas. Bonus: Permanent Status Resist +1.",
	},
	"達成(クリア時)　ヘルマン魔人２撃破　★異常レジスト＋１" = {
		種類 = 10,
		ボーナス = "異常レジスト＋１",
		値 = (list) { "達成／ヘルマン魔人２" },
		説明 = "Achieved (on Clear) - Helman: Two Demon Lords Defeated ★Status Resist +1\nYou defeat two Demon Lords in the same turn while in Helman. Bonus: Permanent Status Resist +1.",
	},
	"達成(クリア時)　ゼス魔人２撃破　　　★異常レジスト＋１" = {
		種類 = 10,
		ボーナス = "異常レジスト＋１",
		値 = (list) { "達成／ゼス魔人２" },
		説明 = "Achieved (on Clear) - Zeth: Two Demon Lords Defeated ★Status Resist +1\nYou defeat two Demon Lords in the same turn while in Zeth. Bonus: Permanent Status Resist +1.",
	},
	"達成(クリア時)　自由都市魔人２撃破　★異常レジスト＋１" = {
		種類 = 10,
		ボーナス = "異常レジスト＋１",
		値 = (list) { "達成／自由都市魔人２" },
		説明 = "Achieved (on Clear) - Free Cities: Two Demon Lords Defeated ★Status Resist +1\nYou defeat two Demon Lords in the same turn in the Free Cities. Bonus: Permanent Status Resist +1.",
	},
	"達成(クリア時)　レイタイマン撃破　　★割り込み発生率＋１" = {
		種類 = 10,
		ボーナス = "割り込み発動＋１",
		値 = (list) { "達成／レイタイマン撃破" },
		説明 = "Achieved (on Clear) - Ray Duel Victory ★Interrupt Rate +1\nRance defeats the Demon Lord Ray in single combat. Bonus: Permanent Interrupt Rate +1.",
	},
	"達成(クリア時)　姉妹撃破　　　　　　★割り込み発生率＋１" = {
		種類 = 10,
		ボーナス = "割り込み発動＋１",
		値 = (list) { "達成／姉妹撃破" },
		説明 = "Achieved (on Clear) - Saizel & Hausel Defeated ★Interrupt Rate +1\nYou defeat the Saizel-Hausel sisters. Bonus: Permanent Interrupt Rate +1.",
	},
	"達成(クリアＡ時)　ワンニャン　　　　★割り込み発生率＋１" = {
		種類 = 10,
		ボーナス = "割り込み発動＋１",
		値 = (list) { "達成／ケイブニャン" },
		説明 = "Achieved (Clear A) - Wan-Nyan ★Interrupt Rate +1\nYou choose “Kave-nyan” and clear the game to the end. Bonus: Permanent Interrupt Rate +1.",
	},
	"達成(クリアＡ時)　恋人美樹　　　　　★割り込み発生率＋１" = {
		種類 = 10,
		ボーナス = "割り込み発動＋１",
		値 = (list) { "達成／恋人美樹" },
		説明 = "Achieved (Clear A) - Lover Miki ★Interrupt Rate +1\nYou clear the game with Miki as Rance's lover. Bonus: Permanent Interrupt Rate +1.",
	},
	"達成(クリア時)　リーザス解放　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／リーザス解放" },
		説明 = "Achieved (on Clear) - Rizeas Liberated ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Rizeas Army casualties reduced by 10%.",
	},
	"達成(クリア時)　リーザス４０枚　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／リーザス３３" },
		説明 = "Achieved (on Clear) - Rizeas 40 Cards ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Rizeas Army casualties reduced by 10%.",
	},
	"達成(クリア時)　ヘルマン解放　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ヘルマン解放" },
		説明 = "Achieved (on Clear) - Helman Liberated ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Helman Army casualties reduced by 10%.",
	},
	"達成(クリア時)　ヘルマン４０枚　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ヘルマン３３" },
		説明 = "Achieved (on Clear) - Helman 40 Cards ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Helman Army casualties reduced by 10%.",
	},
	"達成(クリア時)　ゼス解放　　　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ゼス解放" },
		説明 = "Achieved (on Clear) - Zeth Liberated ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Zeth Army casualties reduced by 10%.",
	},
	"達成(クリア時)　ゼス４０枚　　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ゼス３３" },
		説明 = "Achieved (on Clear) - Zeth 40 Cards ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Zeth Army casualties reduced by 10%.",
	},
	"達成(クリア時)　自由都市解放　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／自由都市解放" },
		説明 = "Achieved (on Clear) - Free Cities Liberated ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Free Cities Army casualties reduced by 10%.",
	},
	"達成(クリア時)　自由都市４０枚　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／自由都市３３" },
		説明 = "Achieved (on Clear) - Free Cities 40 Cards ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Free Cities Army casualties reduced by 10%.",
	},
	"達成(クリア時)　ＪＡＰＡＮ４０枚　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／ＪＡＰＡＮ３３" },
		説明 = "Achieved (on Clear) - JAPAN 40 Cards ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Human casualty rate is reduced.",
	},
	"達成(クリア時)　その他４０枚　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／その他３３" },
		説明 = "Achieved (on Clear) - Other 40 Cards ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Human casualty rate is reduced.",
	},
	"達成(クリア時)　亜人４０枚　　　　　●有利クエスト発生" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／亜人３３" },
		説明 = "Achieved (on Clear) - Demi-humans 40 Cards ●Favorable Quest Appears\nA base event (CP achievement effect activation) occurs. Human casualty rate is reduced.",
	},
	"達成(クリアＡ時)　４地域無事　　　　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／４地域無事" },
		説明 = "Achieved (Clear A) - Four Regions Safe ●?? Unlock Requirement\nPart 2 becomes available once all ?? unlock conditions are met.",
	},
	"達成(クリアＡ時)　ケイブリス撃破　　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／ケイブリス撃破" },
		説明 = "Achieved (Clear A) - Kayblis Defeated ●?? Unlock Requirement\nPart 2 becomes available once all ?? unlock conditions are met.",
	},
	"達成(クリアＡ時)　ホーネット無事　　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／ホーネット無事" },
		説明 = "Achieved (Clear A) - Hornet Safe ●?? Unlock Requirement\nPart 2 becomes available once all ?? unlock conditions are met.",
	},
	"達成(クリアＡ時)　魂管理局との邂逅　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／魂管理局との邂逅" },
		説明 = "Achieved (Clear A) - Encounter with the Soul Bureau ●?? Unlock Requirement\nPart 2 becomes available once all ?? unlock conditions are met.",
	},
	"達成(クリアＡ時)　法王特典未使用　　●？？解放条件" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "条件Ｘ／法王特典未使用" },
		説明 = "Achieved (Clear A) - Pope Bonus Unused ●?? Unlock Requirement\nPart 2 becomes available once all ?? unlock conditions are met.",
	},
	"達成(２部クリア時)　親友は長田君" = {
		種類 = 10,
		値 = (list) { "ルート／長田君" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Nagata\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友は志津香＆ナギ" = {
		種類 = 10,
		値 = (list) { "ルート／志津香＆ナギ" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friends: Shizuka & Nagi\nYou complete your adventure together with your closest friends.",
	},
	"達成(２部クリア時)　親友はリセット" = {
		種類 = 10,
		値 = (list) { "ルート／リセット" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Reset\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友はザンス" = {
		種類 = 10,
		値 = (list) { "ルート／ザンス" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Zance\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友はウズメ" = {
		種類 = 10,
		値 = (list) { "ルート／ウズメ" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Uzume\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友は乱義" = {
		種類 = 10,
		値 = (list) { "ルート／乱義" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Rangyi\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友は深根" = {
		種類 = 10,
		値 = (list) { "ルート／深根" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Fukane\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友はミックス" = {
		種類 = 10,
		値 = (list) { "ルート／ミックス" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Mix\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友はスシヌ" = {
		種類 = 10,
		値 = (list) { "ルート／スシヌ" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Sushinu\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友は元就" = {
		種類 = 10,
		値 = (list) { "ルート／元就" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Motonari\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友はレリコフ" = {
		種類 = 10,
		値 = (list) { "ルート／レリコフ" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Relikov\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友はダークランス" = {
		種類 = 10,
		値 = (list) { "ルート／ダークランス" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Dark Rance\nYou complete your adventure together with your closest friend.",
	},
	"達成(２部クリア時)　親友はドッス＆ワッス" = {
		種類 = 10,
		値 = (list) { "ルート／ドッス＆ワッス" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friends: Doss & Wass\nYou complete your adventure together with your closest friends.",
	},
	"達成(２部クリア時)　親友は松下姫" = {
		種類 = 10,
		値 = (list) { "ルート／松下姫" },
		隠し表示 = 1,
		説明 = "Achieved (Part 2 Clear) - Best Friend: Princess Matsushita\nYou complete your adventure together with your closest friend.",
	},
	集結　ランスバリエーション = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "Lv42 ランス", "Lv45 ランス", "Lv65 ランス", "Lv55 ランス", "全裸 ランス", "タイニー ランス" },
	},
	集結　ランス城のメイドと騎士 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ビスケッタ", "クリン", "ハイジ", "ロナ", "サーナキア", "クルーチェ" },
	},
	集結　運命の女１ = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "運命の女 フェリス", "運命の女 山本五十六", "運命の女 パステル", "運命の女 リア", "運命の女 マジック", "運命の女 志津香", "運命の女 戦姫" },
	},
	集結　運命の女２ = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "運命の女 毛利てる", "運命の女 ミラクル", "運命の女 シーラ", "運命の女 かなみ", "運命の女 チルディ", "運命の女 シィル" },
	},
	集結　フロストバイン一派 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "フロストバイン", "タマ", "あてな２号", "量産型あてな２号" },
	},
	集結　エターナルヒーロー = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ブリティシュ", "カフェ", "日光", "魔剣 カオス", "ホ・ラガ" },
	},
	集結　ＡＬ教 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "クルックー", "ロードリング", "ＢＳ", "セル" },
	},
	集結　リーザス王家 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "リア", "マリス", "かなみ" },
	},
	集結　リーザス軍 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "バレス", "コルドバ", "エクス", "リック", "メナド", "キンケード", "チャカ", "アールコート" },
	},
	集結　リーザス親衛隊 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "レイラ", "チルディ", "ジュリア", "イベット" },
	},
	集結　ヘルマン共和国 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "シーラ", "ペルエレ", "フレイア" },
	},
	集結　ヘルマン軍 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ヒューバート", "ロレックス", "アミトス", "クリーム", "トルストイ", "オルオレ" },
	},
	集結　パットン一派 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "パットン", "ハンティ", "キャンテル" },
	},
	集結　ゼス王国 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "マジック", "ガンジー", "カオル", "ウィチタ", "チョチョマン", "ウルザ" },
	},
	集結　ゼス軍 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "千鶴子", "アニス", "アレックス", "サイアス", "ウスピラ", "カバッハーン" },
	},
	"集結　カスタムの４魔女(R2)" = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "子供志津香", "マリア", "ミル", "エレノア" },
	},
	集結　７人の都市長 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "パパデマス", "パトリシア", "ビヨンホウ", "ペスポ", "エレノア", "コパンドン", "カチューシャ" },
	},
	集結　パランチョ王国 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ポロン", "ピッテン" },
	},
	集結　ＪＰ毛利家 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "てる", "きく", "ちぬ" },
	},
	集結　ＪＰ上杉家 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "謙信", "愛", "勝子", "虎子" },
	},
	集結　妖怪軍団 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "政宗", "お町", "ノワール", "野菊", "折女", "黒部" },
	},
	集結　カラー一族 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "パステル", "サクラ", "イージス", "リセット", "フル", "ビビッド", "モダン" },
	},
	集結　ポピンズ一族 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "三菱王", "満鉄王", "日立姫", "東芝王子" },
	},
	集結　ホルス一族 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "テラ", "メガッス", "メガワス", "メガフォース" },
	},
	集結　聖魔教団 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "シーラ", "闘将Ａ", "闘将Ｂ", "闘将Ｃ", "ゼータ", "シグマ", "キャンテル" },
	},
	集結　マエリータ隊 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "王様", "剣豪", "アパッチ", "学者", "マッスル", "ニードル" },
	},
	集結　ハニー一族 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ハニーキング", "ハニ子", "グリーンハニー", "ブルーハニー", "レッドハニー" },
	},
	集結　日本の人達 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "美樹", "健太郎", "大野喜郎さん", "長堀橋貞夫君", "東大寺久美" },
	},
	集結　ホーネット派 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ホーネット", "サテラ", "ハウゼル", "シルキィ" },
	},
	集結　ケッセルのメイド達 = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "アルカリア", "リリム", "加奈代", "エルシール", "シャロン", "ファーレン", "バーバラ", "パレロア" },
	},
	集結　聖女モンスター = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "ベゼルアイ大", "ウェンリーナー大", "セラクロラス大", "ハウセスナース大", "ベゼルアイ小", "ウェンリーナー小", "セラクロラス小", "ハウセスナース小" },
	},
	集結　ドット = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "タイニー ランス", "タイニー シィル", "タイニー ミラクル", "タイニー かなみ", "タイニー ピグ", "タイニー 志津香", "タイニー クルックー", "タイニー パステル" },
	},
	集結　ロードリングの成長 = {
		種類 = 1,
		ボーナス = "",
		値 = (list) { "Lv18 ロードリング", "Lv26 ロードリング", "Lv31 ロードリング", "Lv37 ロードリング" },
	},
	集結　女の子モンスター１ = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "きゃんきゃん", "フローズン", "メイドさん", "ラルカット", "９７チハ", "幸福きゃんきゃん", "体育スター" },
	},
	集結　女の子モンスター２ = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "シャチ子", "はいからちゃん", "ハチ女", "神風", "バルキリー", "マジスコ", "手裏剣使い" },
	},
	集結　女の子モンスター３ = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "男装女", "鉄腕ラブル", "ミイラン", "上野花子", "めぽら", "ガルバン" },
	},
	集結　次世代モンスター = {
		種類 = 0,
		ボーナス = "",
		値 = (list) { "命の次世代魔物", "大地の次世代魔物", "時の次世代魔物", "力の次世代魔物", "イカマン" },
	},
	"達成(アフター)　１クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター１" },
		説明 = "Achieved (After Mode) - 1 Quest Completed ★Auto-Battle Multiplier +1\nClear at least one Challenge Quest. Bonus: Permanent Auto-Battle Multiplier +1.",
	},
	"達成(アフター)　２クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター２" },
		説明 = "Achieved (After Mode) - 2 Quests Completed ★Auto-Battle Multiplier +1\nClear at least two Challenge Quests. Bonus: Permanent Auto-Battle Multiplier +1.",
	},
	"達成(アフター)　３クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター３" },
		説明 = "Achieved (After Mode) - 3 Quests Completed ★Auto-Battle Multiplier +1\nClear at least three Challenge Quests. Bonus: Permanent Auto-Battle Multiplier +1.",
	},
	"達成(アフター)　４クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター４" },
		説明 = "Achieved (After Mode) - 4 Quests Completed ★Auto-Battle Multiplier +1\nClear at least four Challenge Quests. Bonus: Permanent Auto-Battle Multiplier +1.",
	},
	"達成(アフター)　５クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター５" },
		説明 = "Achieved (After Mode) - 5 Quests Completed ★Auto-Battle Multiplier +1\nClear at least five Challenge Quests. Bonus: Permanent Auto-Battle Multiplier +1.",
	},
	"達成(アフター)　６クエスト達成　　　★自動戦闘倍率＋１" = {
		種類 = 10,
		ボーナス = "自動戦闘倍率＋１",
		値 = (list) { "達成／アフター６" },
		説明 = "Achieved (After Mode) - 6 Quests Completed ★Auto-Battle Multiplier +1\nClear at least six Challenge Quests. Bonus: Permanent Auto-Battle Multiplier +1.",
	},
	"達成(アフター)　バスワルド　　　　　●キャラカード解放" = {
		種類 = 10,
		ボーナス = "",
		値 = (list) { "達成／バスワルド" },
		説明 = "Achieved (After Mode) - Baswald ●Character Card Unlock\nCalm the Second-Class God Baswald. Bonus: Card appears in ‘Anything Goes' mode.",
	},
};