tree 秘書情報 = {
	シィル = {
		フラグ = 1,
		プロフィール = "Lv35 シィル",
	},
	ビスケッタ = {
		フラグ = 1,
		プロフィール = "Lv38 ビスケッタ",
	},
	バレス = {
		フラグ = 1,
		プロフィール = "Lv37 バレス",
	},
	志津香＆ナギ = {
		フラグ = 1,
		プロフィール = {
			フルネーム = "Shizuka & Nagi",
			レベル = "４３",
			身長 = "132 & 131cm",
			体重 = "23 & 25kg",
			職業 = "Custom Citizens",
			スキル = "Magic 2",
			コメント１ = "Half-sisters, their mother's name was Asmaase.",
			コメント２ = "Shizuka took revenge on her father's killer,",
			コメント３ = "Ragarl, and his daughter, Nagi, in turn, swore",
			コメント４ = "revenge on Shizuka. The chain of vengeance has",
			コメント５ = "now been broken, and the two are very close.",
		},
		画像名 = "立ち／子供志津香とナギ／基本",
	},
	サテラ = {
		フラグ = 1,
		プロフィール = "魔人 サテラ",
	},
	ケイブワン＆ニャン = {
		フラグ = 1,
		プロフィール = {
			フルネーム = "Kaybwan & Kaybnyan",
			レベル = "13 & 8",
			身長 = "131 & 128cm",
			体重 = "29 & 15kg",
			職業 = "Apostles",
			スキル = "",
			コメント１ = "Two loyal apostles created by the",
			コメント２ = "Dark Lord Kayblis.",
			コメント３ = "",
			コメント４ = "But they're completely incompetent.",
			コメント５ = "",
		},
		画像名 = "立ち／ケイブワン＆ニャン／基本",
	},
	長田君 = {
		フラグ = 2,
		プロフィール = "Lv22 長田君",
		画像名 = "立ち／長田君２／基本",
	},
	リセット = {
		フラグ = 2,
		プロフィール = "Lv63 リセット",
		画像名 = "立ち／リセット２／基本",
	},
	母クルックー = {
		フラグ = 2,
		プロフィール = {
			フルネーム = "Crook Mofus",
			レベル = "４０",
			年齢 = "３３歳",
			身長 = "１５８ｃｍ",
			体重 = "？？",
			職業 = "AL Church Pope, Mother",
			スキル = "Divine Magic 3, Adventure 1",
			コメント１ = "The AL Church's pope.",
			コメント２ = "",
			コメント３ = "She gave birth to you in RA02, and has",
			コメント４ = "raised you as your mother ever since.",
			コメント５ = "",
		},
		画像名 = "立ち／クルックー２／基本",
	},
	アリス = {
		フラグ = 0,
		プロフィール = {
			フルネーム = "Alice",
			レベル = "？？",
			身長 = "？？？",
			体重 = "？？？",
			職業 = "Poster Girl",
			スキル = "？？？",
			コメント１ = "You can change your assistant from this screen.",
			コメント２ = "",
			コメント３ = "Other characters will be added from time",
			コメント４ = "to time, so please look forward to them.",
			コメント５ = "",
		},
	},
	クゥ = {
		フラグ = 1,
		プロフィール = {
			フルネーム = "QD",
			レベル = "？？",
			年齢 = "",
			身長 = "１５０ｃｍ",
			体重 = "？？？",
			職業 = "？？？",
			スキル = "？？？",
			コメント１ = "Fwahahahahaha!",
			コメント２ = "I can't believe you noticed me!",
			コメント３ = "I'm secretly making my debut as",
			コメント４ = "an assistant!",
			コメント５ = "",
		},
		画像名 = "立ち／クゥ／基本／笑顔",
	},
};