table 立ち絵名札マッピング情報 = {
	{ indexed string stand, string name },
	{ "アーシー／", "Arshie Julieta" },
	{ "アームズ／", "Arms Ark" },
	{ "アールコート／", "Arlcoate Marius" },
	{ "アギレダ", "Agireda Koisabushi Zonna Abona" },
	{ "アスカ／", "Asuka Cadmium" },
	{ "アタゴ", "Atago Makatt" },
	{ "アトランタ／", "Atlanta" },
	{ "アナセル／", "Anasel Caspola" },
	{ "アニス／", "Anise Sawatari" },
	{ "アミトス／", "Amitos Amiteige" },
	{ "アム／", "Am Isuel" },
	{ "アルカネーゼ／", "Arcanese Rise" },
	{ "アルカリア／", "Arcalia" },
	{ "アレックス／", "Alex Vals" },
	{ "アレフガルド／", "Alefgard" },
	{ "イアン／", "Ian Ruston" },
	{ "イージス／", "Aegis Kalar" },
	{ "イオ／", "Io Ishtar" },
	{ "イカンティ／", "Ikanti Kalar" },
	{ "ウィチタ／", "Wichita Skate" },
	{ "ウィリス／", "Willis Fujisaki" },
	{ "ウェンリーナー小／", "Wenlina" },
	{ "ウェンリーナー大／", "Wenlina" },
	{ "ウスピラ／", "Uspira Mafuyu" },
	{ "ウルザ／", "Urza Pranaice" },
	{ "エクス／", "Ex Banquet" },
	{ "エルシール／", "Elsheele" },
	{ "エレナ／", "Elena Flower" },
	{ "エレノア／", "Eleanor Ran" },
	{ "エロピチャ／", "Eropicha Nyanko" },
	{ "オーロラ／", "Aurora" },
	{ "オノハ／", "Onoha Mespos" },
	{ "オルオレ／", "Oluore the Third" },
	{ "カオス／", "Chaos" },
	{ "カオル／", "Kaoru Quincy Kagura" },
	{ "カスミ／", "Kasumi K. Kasumi" },
	{ "カチューシャ／", "Katyusha Bosch" },
	{ "少女カチューシャ", "Katyusha Bosch" },
	{ "かなみ／", "Kanami Kentou" },
	{ "カバッハーン／", "Kabachaan the Lightning" },
	{ "カフェ／", "Cafe Artful" },
	{ "カミーラ／", "Camilla" },
	{ "ガルティア／", "Galtia" },
	{ "カロリア／", "Caloria Cricket" },
	{ "ガンジー／", "Ragnarokarc Super Gandhi" },
	{ "きく／", "Kikukawa Kiku" },
	{ "キムチ／", "Kimchi Drive" },
	{ "キャロリ／", "Caroli Mate" },
	{ "キラトーキ／", "Kirato-ki" },
	{ "キンケード／", "Kinkaid Brambla" },
	{ "クリーム／", "Cream Ganoblade" },
	{ "クリン／", "Klin Byu" },
	{ "クルーチェ／", "Cruche Muffin" },
	{ "クルックー／", "Crook Mofus" },
	{ "クレイン／", "Crane" },
	{ "ケイコ／", "Keiko" },
	{ "ケイブニャン／", "Kaybnyan" },
	{ "ケイブリス／", "Kayblis" },
	{ "ケイブワン／", "Kaybwan" },
	{ "ケッセルリンク／", "Kesselring" },
	{ "コパンドン／", "Copandon Dot" },
	{ "コルドバ／", "Cordoba Burn" },
	{ "コンバート／", "Convert Tax" },
	{ "サーナキア／", "Sanakia Drelschkaf" },
	{ "サイアス／", "Saias Crown" },
	{ "サイゼル／", "La Seizel" },
	{ "サクラ／", "Sakura Kalar" },
	{ "サチコ／", "Sachiko Centers" },
	{ "サテラ／", "Satella" },
	{ "サメザン／", "Samezan" },
	{ "ジーク／", "Zeke" },
	{ "シーラ／", "Sheila Helman" },
	{ "シィル／", "Sill Plain" },
	{ "ジャロ／", "Jallo Jasrak" },
	{ "シャロン／", "Sharon" },
	{ "ジュノー／", "Juno" },
	{ "ジュリア／", "Julia Lindam" },
	{ "シルキィ／", "Silky Little Raisin" },
	{ "スー／", "Sue Provence" },
	{ "セシル／", "Cecil Karna" },
	{ "セラクロラス小／", "Serachloras" },
	{ "セラクロラス大／", "Serachloras" },
	{ "セル／", "Sel Karchgolf" },
	{ "タルゴ／", "Targo" },
	{ "ちぬ／", "Chinu Kobayakawa" },
	{ "チャカ／", "Chaka Cadmium" },
	{ "チョチョマン／", "Chocho Man Publy" },
	{ "チルディ／", "Tilde Sharp" },
	{ "テオマン／", "Arios Theoman" },
	{ "テラ／", "Tera Horus" },
	{ "てる／", "Mouri Teru" },
	{ "ニミッツ／", "Nimitz Leek" },
	{ "ニミッツレキシントン２／基本", "Nimitz Leek" },
	{ "ニミッツレキシントン２／心の声", "Nimitz Leek" },
	{ "ヌヌハラ／", "Nunuhara Cabbage" },
	{ "ネプラカス本体／", "Neprakas" },
	{ "ネルソン／", "Nelson Server" },
	{ "ノア／", "Noah Hakobune" },
	{ "ノーマルホルス／", "Horus" },
	{ "バード／", "Bird Lithfie" },
	{ "バーナード／", "Bernard Ceramite" },
	{ "バーバラ／", "Barbara" },
	{ "パイアール／", "Paiarl" },
	{ "パイアールロボ／", "Paiarl" },
	{ "ハイジ／", "Heidi Pankrauw" },
	{ "ハウセスナース小／", "Housesnurse" },
	{ "ハウセスナース大／", "Housesnurse" },
	{ "ハウゼル／", "La Hawzel" },
	{ "ハウレーン／", "Haurein Province" },
	{ "パステル／", "Pastel Kalar" },
	{ "バスワルド／", "La Baswald" },
	{ "パセリ／", "Parsley Rig Zeth" },
	{ "パセリ幽霊／", "Parsley Rig Zeth" },
	{ "パットン／", "Patton Helman" },
	{ "パトリシア／", "Patricia Bacon" },
	{ "パパイア／", "Papaya Server" },
	{ "パパデマス／", "Papademas Silsabun" },
	{ "バボラ／", "Babora" },
	{ "バレス／", "Barres Province" },
	{ "パレロア／", "Paleror" },
	{ "ハンティ／", "Hunty Kalar" },
	{ "ピグ／", "Pigu Geliciam" },
	{ "ビスケッタ／", "Bisketta Bernes" },
	{ "ピッテン／", "Pitten Chao" },
	{ "ビビッド／", "Vivid Kalar" },
	{ "ビビッド幽霊／", "Vivid Kalar" },
	{ "ヒューバート／", "Hubert Lipton" },
	{ "ビヨンホウ／", "Byonhou Osman" },
	{ "ファーレン／", "Fahren" },
	{ "フル／", "Full Kalar" },
	{ "フル幽霊／", "Full Kalar" },
	{ "フレイア／", "Freia Izun" },
	{ "ペスポ／", "Pespo Tontone" },
	{ "ベゼルアイ小／", "Bezeleye" },
	{ "ベゼルアイ大／", "Bezeleye" },
	{ "ペルエレ／", "Perelle Calet" },
	{ "ホーネット／", "Hornet" },
	{ "ポロン／", "Poron Chao" },
	{ "マーシー／", "Marcy Julieta" },
	{ "マジック／", "Magic the Gandy" },
	{ "ますぞえ／", "Masuzoe" },
	{ "マリア／", "Maria Custard" },
	{ "マリス／", "Maris Amaryllis" },
	{ "マルチナ／", "Martina Curry" },
	{ "ミステリア／", "Mysteria To" },
	{ "ミラクル／", "Miracle To" },
	{ "ミル／", "Mill Yorks" },
	{ "メアリー／", "Mary Ann" },
	{ "メアリー２／", "Mary Ann" },
	{ "メイドロナ／", "Rona Keshtina" },
	{ "メガッス／", "Megas Horus" },
	{ "メガフォース／", "Megaforce Horus" },
	{ "メガワス／", "Megawas Horus" },
	{ "メディウサ／", "Medusa" },
	{ "メナド／", "Menad Shisei" },
	{ "メリム／", "Merim Tzeel" },
	{ "メルフェイス／", "Melfeis Promenade" },
	{ "モダン／", "Modern Kalar" },
	{ "モダン幽霊／", "Modern Kalar" },
	{ "ユーティン／", "Yutin Fulls" },
	{ "ユキ／", "Yuki" },
	{ "ラウネア／", "Launea" },
	{ "ラッシー／", "Lassie" },
	{ "リア／", "Lia Parapara Leazas" },
	{ "リズナ／", "Rizna Lanfbitt" },
	{ "リセット／", "Reset Kalar" },
	{ "リック／", "Rick Addison" },
	{ "リトルプリンセス／", "Demon King Little Princess" },
	{ "リリム／", "Lilim" },
	{ "ルーシー／", "Lucy Julieta" },
	{ "ルート／", "Route Ari" },
	{ "ルート肉片／", "Meat Chunk" },
	{ "ルーベラン／", "Ruberan Tzeel" },
	{ "レイ／", "Ray" },
	{ "レイラ／", "Layla Grekni" },
	{ "レキシントン２／", "Lexington" },
	{ "レッドアイアニス／", "RedEye" },
	{ "レッドアイトッポス／", "RedEye" },
	{ "レッドアイ魔法魔物兵／", "RedEye" },
	{ "ロードリング／", "Mi Lordring" },
	{ "ロッキー／", "Rocky Bank" },
	{ "ロナ／", "Rona Keshtina" },
	{ "ロレックス／", "Rolex Gadras" },
	{ "ワーグ／", "Warg" },
	{ "香姫", "Oda Kouhime" },
	{ "愛／", "Naoe Ai" },
	{ "加奈代／", "Kanayo" },
	{ "火炎書士／", "Flame Scribe" },
	{ "花屋エレナ／", "Elena Flower" },
	{ "健太郎／", "Ogawa Kentarou" },
	{ "謙信／", "Uesugi Kenshin" },
	{ "虎子／", "Uesugi Torako" },
	{ "五十六／", "Yamamoto Isoroku" },
	{ "子供ナギ／", "Nagi su Ragarl" },
	{ "子供志津香／", "Maso Shizuka" },
	{ "子供志津香とナギ／", "Shizuka and Nagi" },
	{ "篠田源五郎／", "Shinoda Gengorou" },
	{ "女ケッセルリンク／", "Kesselring" },
	{ "勝子／", "Uesugi Katsuko" },
	{ "政宗／", "Dokuganryuu Masamune" },
	{ "千鶴子／", "Yamada Chizuko" },
	{ "千姫／", "Tokugawa Chi" },
	{ "早雲／", "Houjou Soun" },
	{ "朝倉義景／", "Asakura Yoshikage" },
	{ "超人アギレダ／", "Agireda Koisabushi Zonna Abona" },
	{ "透琳／", "Sanada Tourin" },
	{ "日光刀／", "Nikkou" },
	{ "日立姫／", "Hitachihime" },
	{ "日立姫砂漠案内人／", "Desert Guide" },
	{ "汎用カラー／", "Kalar" },
	{ "汎用グリーンハニー／", "Green Hanny" },
	{ "汎用ゼス女魔法兵／", "Zeth Mage Soldier" },
	{ "汎用ゼス男魔法兵／", "Zeth Mage Soldier" },
	{ "汎用テンプルナイト／", "Temple Knight" },
	{ "汎用ハニー／", "Hanny" },
	{ "汎用ブラックハニー／", "Black Hanny" },
	{ "汎用ブルーハニー／", "Blue Hanny" },
	{ "汎用ヘルマン騎士／", "Helman Knight" },
	{ "汎用ヘルマン兵／", "Helman Soldier" },
	{ "汎用ランス城騎士／", "Rance Castle Knight" },
	{ "汎用リーザス黒騎士／", "Leazas Black Knight" },
	{ "汎用リーザス黒兵／", "Leazas Black Soldier" },
	{ "汎用リーザス親衛隊／", "Leazas Royal Guard" },
	{ "汎用リーザス青騎士／", "Leazas Blue Knight" },
	{ "汎用リーザス青兵／", "Leazas Blue Soldier" },
	{ "汎用リーザス赤騎士／", "Leazas Red Knight" },
	{ "汎用リーザス赤兵／", "Leazas Red Soldier" },
	{ "汎用リーザス白騎士／", "Leazas White Knight" },
	{ "汎用リーザス白兵／", "Leazas White Soldier" },
	{ "汎用レッドハニー／", "Red Hanny" },
	{ "汎用筋肉男／", "Muscle Man" },
	{ "汎用穴奴隷／", "Slave in Hole" },
	{ "汎用自由都市警備兵Ａ／", "Free City Guard A" },
	{ "汎用自由都市警備兵Ｂ／", "Free City Guard B" },
	{ "汎用女／", "Woman" },
	{ "汎用女ポピンズ１／", "Poppins 1" },
	{ "汎用女ポピンズ２／", "Poppins 2" },
	{ "汎用女武士兵／", "JAPAN Samurai" },
	{ "汎用少女／", "Girl" },
	{ "汎用少年／", "Boy" },
	{ "汎用男／", "Man" },
	{ "汎用男ポピンズ１／", "Poppins" },
	{ "汎用男ポピンズ２／", "Poppins" },
	{ "汎用男武士兵／", "JAPAN Samurai" },
	{ "汎用天使／", "Angel" },
	{ "汎用闘将Ａ／", "Battle General" },
	{ "汎用闘将Ｂ／", "Battle General" },
	{ "汎用闘将Ｃ／", "Battle General" },
	{ "汎用婆／", "Old Woman" },
	{ "汎用飛行魔物兵／", "Flying Demon Soldier" },
	{ "汎用武将／", "JAPAN Warlord" },
	{ "汎用魔物使い／", "Monster Tamer" },
	{ "汎用魔物将軍／", "Monster General" },
	{ "汎用魔物隊長／", "Monster Captain" },
	{ "汎用魔物兵青／", "Blue Monster Soldier" },
	{ "汎用魔物兵赤／", "Red Monster Soldier" },
	{ "汎用魔物兵緑／", "Green Monster Soldier" },
	{ "汎用魔法魔物兵／", "Magic Monster Soldier" },
	{ "汎用爺／", "Old Man" },
	{ "汎用巫女／", "Shrine Maiden" },
	{ "美樹／", "Kimizu Miki" },
	{ "柚美／", "Yuhara Yumi" },
	{ "女神アリス／", "Goddess Alice" },
	{ "エロヤック／", "Eroyack ALV" },
	{ "海獣レイド／", "Sea Beast Raid Boss" },
	{ "汎用弓兵／", "Archer" },
	{ "汎用戦士／", "Warrior" },
	{ "汎用東ヘルマン兵／", "East Helman Soldier" },
	{ "汎用魔法使い／", "Mage" },
	{ "大地の次世代魔物／", "Hanmaan" },
	{ "命の次世代魔物／", "Kibao" },
	{ "力の次世代魔物／", "Kirekire Takora" },
	{ "時の次世代魔物／", "White Satan" },
	{ "アマデス／", "Amades Kakades" },
	{ "オーギル／", "Ogil Lott Stein" },
	{ "ニーナ／", "Nina Nirvana" },
	{ "シルバレル／", "Silbarrel Silbarella" },
	{ "ドエススキー／", "Don Doessky" },
	{ "トルストイ／", "Tolstoy Bateau" },
	{ "アカシロ／", "Akashiro Kalar" },
	{ "イベット／", "Yvette Cheria" },
	{ "サムソン／", "Samson Maximov" },
	{ "デストラー／", "Bintang Destler" },
	{ "エール２／", "Aile Mofs" },
	{ "クルックー２／", "Crook Mofus" },
	{ "乱義２／", "Yamamoto Rangy" },
	{ "ザンス２／", "Zance Leazas" },
	{ "ヒーロー２／", "Hero Helman" },
	{ "長田君２／", "Osada-kun" },
	{ "ロッキー２／", "Rocky Bank" },
	{ "リセット２／", "Reset Kalar" },
	{ "ナギ２／", "Nagi su Ragarl" },
	{ "志津香２／", "Maso Shizuka" },
	{ "ドッス２／", "Doss" },
	{ "ワッス２／", "Wass" },
	{ "ウズメ２／", "Kentou Uzume" },
	{ "深根２／", "Tokugawa Fukane" },
	{ "ミックス２／", "Mix To" },
	{ "スシヌ２／", "Sushinu the Gandy" },
	{ "レリコフ２／", "Relicov Helman" },
	{ "元就２／", "Mouri Motonari" },
	{ "ダークランス２／", "Dark Rance" },
	{ "マリア２／", "Maria Custard" },
	{ "ランスＪｒ／", "Rance Jr." },
	{ "ドギ２／", "Dogi Magi" },
	{ "アームズ２／", "Arms Ark" },
	{ "マジック２／", "Magic the Gandy" },
	{ "シーラ２／", "Sheila Helman" },
	{ "リア２／", "Lia Parapara Leazas" },
	{ "ミラクル２／", "Miracle To" },
	{ "ビスケッタ２／", "Bisketta Bernes" },
	{ "コパンドン２／", "Copandon Dot" },
	{ "ヌーク７７２／", "Nuke 77" },
	{ "香姫２／", "Oda Kouhime" },
	{ "タイガー将軍２／", "General Tiger" },
	{ "ランス２／", "Demon King Rance" },
	{ "リズナ２／", "Rizna Lanfbitt" },
	{ "すず２／", "Houjou Suzu" },
	{ "早雲２／", "Houjou Soun" },
	{ "シュリ２／", "Shuri Seihajuu Nagasaki" },
	{ "ケイブリス２／", "K-Chan" },
	{ "アレキサンダー２／", "Alexander" },
	{ "魔人ＤＤ／", "DD" },
	{ "魔女リクチェル／", "Rikcher von do Korthus" },
	{ "バイタル／", "Vital Fit" },
	{ "ドギ／", "Dogi Magi" },
	{ "汎用売春宿ボーイ／", "Brothel Boy" }
};