table 立ち絵名札マッピング情報 = {
	{ indexed string stand, string name },
	{ "アーシー／", "Arcy Julietta" },
	{ "アームズ／", "Arms Arc" },
	{ "アールコート／", "Arlcourt Marius" },
	{ "アギレダ", "Agireda Coisabussi Zon'na Abona" },
	{ "アスカ／", "Asuka Cadmium" },
	{ "アタゴ", "Atago Makat" },
	{ "アトランタ／", "Atlanta" },
	{ "アナセル／", "Anasel Caspora" },
	{ "アニス／", "Anis Sawatari" },
	{ "アミトス／", "Amithos Armitage" },
	{ "アム／", "Am Isuel" },
	{ "アルカネーゼ／", "Arcanese Rise" },
	{ "アルカリア／", "Alcalia" },
	{ "アレックス／", "Alex Vals" },
	{ "アレフガルド／", "Alefgard" },
	{ "イアン／", "Ian Ruston" },
	{ "イージス／", "Aegis Kalar" },
	{ "イオ／", "Io Ishtar" },
	{ "イカンティ／", "Icanty Kalar" },
	{ "ウィチタ／", "Wichita Skate" },
	{ "ウィリス／", "Willis Fujisaki" },
	{ "ウェンリーナー小／", "Wenliner" },
	{ "ウェンリーナー大／", "Wenliner" },
	{ "ウスピラ／", "Uspira Mafuyu" },
	{ "ウルザ／", "Urza Pranaice" },
	{ "エクス／", "Ex Banquet" },
	{ "エルシール／", "Elseal" },
	{ "エレナ／", "Elena Flower" },
	{ "エレノア／", "Eleanor Lan" },
	{ "エロピチャ／", "Eropicha Nyanko" },
	{ "オーロラ／", "Aurora" },
	{ "オノハ／", "Onoha Mespos" },
	{ "オルオレ／", "Oruore the Third" },
	{ "カオス／", "Chaos" },
	{ "カオル／", "Kaoru Quincy Kagura" },
	{ "カスミ／", "Kasumi K. Kasumi" },
	{ "カチューシャ／", "Katyusha Bosch" },
	{ "少女カチューシャ", "Katyusha Bosch" },
	{ "かなみ／", "Kentou Kanami" },
	{ "カバッハーン／", "Kavahan the Lightning" },
	{ "カフェ／", "Cafe Artful" },
	{ "カミーラ／", "Camilla" },
	{ "ガルティア／", "Galtia" },
	{ "カロリア／", "Kaloria Cricket" },
	{ "ガンジー／", "Ragnarokarc Super Gandhi" },
	{ "きく／", "Kikkawa Kiku" },
	{ "キムチ／", "Kimchi Drive" },
	{ "キャロリ／", "Caroly Mate" },
	{ "キラトーキ／", "Kiratoki" },
	{ "キンケード／", "Kinkade Brumbler" },
	{ "クリーム／", "Cream Ganoblade" },
	{ "クリン／", "Clin Biu" },
	{ "クルーチェ／", "Cruche Muffin" },
	{ "クルックー／", "Kruku Mooths" },
	{ "クレイン／", "Crane" },
	{ "ケイコ／", "Keiko" },
	{ "ケイブニャン／", "Cave-Nyan" },
	{ "ケイブリス／", "Kayblis" },
	{ "ケイブワン／", "Cave-One" },
	{ "ケッセルリンク／", "Kesselring" },
	{ "コパンドン／", "Copandon Dot" },
	{ "コルドバ／", "Cordoba Burn" },
	{ "コンバート／", "Convert Tacks" },
	{ "サーナキア／", "Sanakia Drelschkaf" },
	{ "サイアス／", "Sias Crown" },
	{ "サイゼル／", "La Saizel" },
	{ "サクラ／", "Sakura Kalar" },
	{ "サチコ／", "Sachiko Centers" },
	{ "サテラ／", "Satella" },
	{ "サメザン／", "Samezan" },
	{ "ジーク／", "Zeke" },
	{ "シーラ／", "Sheila Hellman" },
	{ "シィル／", "Sill Plain" },
	{ "ジャロ／", "Jarro Jaslac" },
	{ "シャロン／", "Sharon" },
	{ "ジュノー／", "Junoe" },
	{ "ジュリア／", "Julia Lindam" },
	{ "シルキィ／", "Silky Little Laisen" },
	{ "スー／", "Sue Provence" },
	{ "セシル／", "Cecil Kana" },
	{ "セラクロラス小／", "Serachloras" },
	{ "セラクロラス大／", "Serachloras" },
	{ "セル／", "Cell Karchgolf" },
	{ "タルゴ／", "Targo" },
	{ "ちぬ／", "Kobayakawa Chinu" },
	{ "チャカ／", "Chaka Cadmium" },
	{ "チョチョマン／", "Chochoman Publi" },
	{ "チルディ／", "Childy Sharp" },
	{ "テオマン／", "Arios Theoman" },
	{ "テラ／", "Tera Horus" },
	{ "てる／", "Mouri Teru" },
	{ "ニミッツ／", "Nimitz Leek" },
	{ "ニミッツレキシントン２／基本", "Nimitz Leek" },
	{ "ニミッツレキシントン２／心の声", "Nimitz Leek" },
	{ "ヌヌハラ／", "Nunuhara Cabbage" },
	{ "ネプラカス本体／", "Neprakus" },
	{ "ネルソン／", "Nelson Server" },
	{ "ノア／", "Noah Hakobune" },
	{ "ノーマルホルス／", "Horus" },
	{ "バード／", "Bard Lisphy" },
	{ "バーナード／", "Bernard Ceramite" },
	{ "バーバラ／", "Barbara" },
	{ "パイアール／", "Paiarl" },
	{ "パイアールロボ／", "Paiarl" },
	{ "ハイジ／", "Heidi Panclow" },
	{ "ハウセスナース小／", "Housesnurse" },
	{ "ハウセスナース大／", "Housesnurse" },
	{ "ハウゼル／", "La Houzel" },
	{ "ハウレーン／", "Haulane Provence" },
	{ "パステル／", "Pastel Kalar" },
	{ "バスワルド／", "La Baswald" },
	{ "パセリ／", "Parsley Rig Zeth" },
	{ "パセリ幽霊／", "Parsley Rig Zeth" },
	{ "パットン／", "Patton Hellman" },
	{ "パトリシア／", "Patricia Bacon" },
	{ "パパイア／", "Papaya Server" },
	{ "パパデマス／", "Papademas Silsabun" },
	{ "バボラ／", "Babola" },
	{ "バレス／", "Bales Provence" },
	{ "パレロア／", "Palerore" },
	{ "ハンティ／", "Hanty Kalar" },
	{ "ピグ／", "Pig Giliusiam" },
	{ "ビスケッタ／", "Bisketta Bernes" },
	{ "ピッテン／", "Pitten Chao" },
	{ "ビビッド／", "Vivid Kalar" },
	{ "ビビッド幽霊／", "Vivid Kalar" },
	{ "ヒューバート／", "Hubert Lipton" },
	{ "ビヨンホウ／", "Biyonhou Osman" },
	{ "ファーレン／", "Fahren" },
	{ "フル／", "Full Kalar" },
	{ "フル幽霊／", "Full Kalar" },
	{ "フレイア／", "Freia Isun" },
	{ "ペスポ／", "Pespo Tontone" },
	{ "ベゼルアイ小／", "Bezel Eye" },
	{ "ベゼルアイ大／", "Bezel Eye" },
	{ "ペルエレ／", "Perelle Carret" },
	{ "ホーネット／", "Hornet" },
	{ "ポロン／", "Poron Chao" },
	{ "マーシー／", "Marcy Julietta" },
	{ "マジック／", "Magic the Gandhi" },
	{ "ますぞえ／", "Masuzoe" },
	{ "マリア／", "Maria Custard" },
	{ "マリス／", "Maris Amaryllis" },
	{ "マルチナ／", "Martina Curry" },
	{ "ミステリア／", "Mysteria Toh" },
	{ "ミラクル／", "Miracle Toh" },
	{ "ミル／", "Mill Yorks" },
	{ "メアリー／", "Mary Ann" },
	{ "メアリー２／", "Mary Ann" },
	{ "メイドロナ／", "Rona Kestina" },
	{ "メガッス／", "Megas Horus" },
	{ "メガフォース／", "Megaforce Horus" },
	{ "メガワス／", "Megawas Horus" },
	{ "メディウサ／", "Medusa" },
	{ "メナド／", "Menad Shisei" },
	{ "メリム／", "Merim Tsel" },
	{ "メルフェイス／", "Melface Promenade" },
	{ "モダン／", "Modern Kalar" },
	{ "モダン幽霊／", "Modern Kalar" },
	{ "ユーティン／", "Yutin Fruz" },
	{ "ユキ／", "Yuki" },
	{ "ラウネア／", "Launea" },
	{ "ラッシー／", "Lassie" },
	{ "リア／", "Lia Parapara Leazas" },
	{ "リズナ／", "Lizzna Lanfbitt" },
	{ "リセット／", "Reset Kalar" },
	{ "リック／", "Rick Addison" },
	{ "リトルプリンセス／", "Demon King Little Princess" },
	{ "リリム／", "Lilim" },
	{ "ルーシー／", "Lucy Julietta" },
	{ "ルート／", "Root Ari" },
	{ "ルート肉片／", "Meat Chunk" },
	{ "ルーベラン／", "Lubelan Tsel" },
	{ "レイ／", "Ray" },
	{ "レイラ／", "Layla Grekney" },
	{ "レキシントン２／", "Lexington" },
	{ "レッドアイアニス／", "Red Eye" },
	{ "レッドアイトッポス／", "Red Eye" },
	{ "レッドアイ魔法魔物兵／", "Red Eye" },
	{ "ロードリング／", "Mi Roadring" },
	{ "ロッキー／", "Rocky Bank" },
	{ "ロナ／", "Rona Kestina" },
	{ "ロレックス／", "Rolex Gadras" },
	{ "ワーグ／", "Warg" },
	{ "香姫", "Oda Kaoru" },
	{ "愛／", "Naoe Ai" },
	{ "加奈代／", "Kanayo" },
	{ "火炎書士／", "Kaenshoshi (Flame Scribe)" },
	{ "花屋エレナ／", "Elena Flower" },
	{ "健太郎／", "Ogawa Kentarou" },
	{ "謙信／", "Uesugi Kenshin" },
	{ "虎子／", "Uesugi Torako" },
	{ "五十六／", "Yamamoto Isoroku" },
	{ "子供ナギ／", "Nagi S. Ragarl" },
	{ "子供志津香／", "Masou Shizuka" },
	{ "子供志津香とナギ／", "Shizuka and Nagi" },
	{ "篠田源五郎／", "Shinoda Gengorou" },
	{ "女ケッセルリンク／", "Kesselring" },
	{ "勝子／", "Uesugi Katsuko" },
	{ "政宗／", "Dokuganryu Masamune" },
	{ "千鶴子／", "Yamada Chizuko" },
	{ "千姫／", "Tokugawa Sen" },
	{ "早雲／", "Hojo Soun" },
	{ "朝倉義景／", "Asakura Yoshikage" },
	{ "超人アギレダ／", "Agireda Coisabussi Zon'na Abona" },
	{ "透琳／", "Sanada Tourin" },
	{ "日光刀／", "Nikko" },
	{ "日立姫／", "Hitachihime" },
	{ "日立姫砂漠案内人／", "Desert Guide" },
	{ "汎用カラー／", "Kalar" },
	{ "汎用グリーンハニー／", "Green Honey" },
	{ "汎用ゼス女魔法兵／", "Zeth Mage Soldier" },
	{ "汎用ゼス男魔法兵／", "Zeth Mage Soldier" },
	{ "汎用テンプルナイト／", "Temple Knight" },
	{ "汎用ハニー／", "Honey" },
	{ "汎用ブラックハニー／", "Black Honey" },
	{ "汎用ブルーハニー／", "Blue Honey" },
	{ "汎用ヘルマン騎士／", "Helman Knight" },
	{ "汎用ヘルマン兵／", "Helman Soldier" },
	{ "汎用ランス城騎士／", "Leazas Castle Knight" },
	{ "汎用リーザス黒騎士／", "Leazas Black Knight" },
	{ "汎用リーザス黒兵／", "Leazas Black Soldier" },
	{ "汎用リーザス親衛隊／", "Leazas Royal Guard" },
	{ "汎用リーザス青騎士／", "Leazas Blue Knight" },
	{ "汎用リーザス青兵／", "Leazas Blue Soldier" },
	{ "汎用リーザス赤騎士／", "Leazas Red Knight" },
	{ "汎用リーザス赤兵／", "Leazas Red Soldier" },
	{ "汎用リーザス白騎士／", "Leazas White Knight" },
	{ "汎用リーザス白兵／", "Leazas White Soldier" },
	{ "汎用レッドハニー／", "Red Honey" },
	{ "汎用筋肉男／", "Muscle Man" },
	{ "汎用穴奴隷／", "Hole Slave" },
	{ "汎用自由都市警備兵Ａ／", "Free City Guard" },
	{ "汎用自由都市警備兵Ｂ／", "Free City Guard" },
	{ "汎用女／", "Woman" },
	{ "汎用女ポピンズ１／", "Poppins" },
	{ "汎用女ポピンズ２／", "Poppins" },
	{ "汎用女武士兵／", "JAPAN Samurai" },
	{ "汎用少女／", "Girl" },
	{ "汎用少年／", "Boy" },
	{ "汎用男／", "Man" },
	{ "汎用男ポピンズ１／", "Poppins" },
	{ "汎用男ポピンズ２／", "Poppins" },
	{ "汎用男武士兵／", "JAPAN Samurai" },
	{ "汎用天使／", "Angel" },
	{ "汎用闘将Ａ／", "Fighter General" },
	{ "汎用闘将Ｂ／", "Fighter General" },
	{ "汎用闘将Ｃ／", "Fighter General" },
	{ "汎用婆／", "Old Woman" },
	{ "汎用飛行魔物兵／", "Flying Monster Soldier" },
	{ "汎用武将／", "JAPAN Warlord" },
	{ "汎用魔物使い／", "Monster Tamer" },
	{ "汎用魔物将軍／", "Monster General" },
	{ "汎用魔物隊長／", "Monster Captain" },
	{ "汎用魔物兵青／", "Blue Monster Soldier" },
	{ "汎用魔物兵赤／", "Red Monster Soldier" },
	{ "汎用魔物兵緑／", "Green Monster Soldier" },
	{ "汎用魔法魔物兵／", "Magic Monster Soldier" },
	{ "汎用爺／", "Old Man" },
	{ "汎用巫女／", "Shrine Maiden" },
	{ "美樹／", "Kurosui Miki" },
	{ "柚美／", "Yuhara Yumi" },
	{ "女神アリス／", "Goddess ALICＥ" },
	{ "エロヤック／", "Eroyack ALV" },
	{ "海獣レイド／", "Sea Beast Raid Boss" },
	{ "汎用弓兵／", "Archer" },
	{ "汎用戦士／", "Warrior" },
	{ "汎用東ヘルマン兵／", "East Helman Soldier" },
	{ "汎用魔法使い／", "Mage" },
	{ "大地の次世代魔物／", "Hanmaan" },
	{ "命の次世代魔物／", "Kibao" },
	{ "力の次世代魔物／", "Kirekiretacola" },
	{ "時の次世代魔物／", "White Satan" },
	{ "アマデス／", "Amades Kakades" },
	{ "オーギル／", "Orgil Lot Stein" },
	{ "ニーナ／", "Nina Nirvana" },
	{ "シルバレル／", "Silverel Silverella" },
	{ "ドエススキー／", "Don Doesuski" },
	{ "トルストイ／", "Tolstoy Bateau" },
	{ "アカシロ／", "Akashiro Kalar" },
	{ "イベット／", "Yvette Cheria" },
	{ "サムソン／", "Samson Maximov" },
	{ "デストラー／", "Bintang Destler" },
	{ "エール２／", "Aile Moofs" },
	{ "クルックー２／", "Kruku Moofs" },
	{ "乱義２／", "Yamamoto Rangii" },
	{ "ザンス２／", "Zance Leazas" },
	{ "ヒーロー２／", "Hero Helman" },
	{ "長田君２／", "Nagata-kun" },
	{ "ロッキー２／", "Rocky Bank" },
	{ "リセット２／", "Reset Kalar" },
	{ "ナギ２／", "Nagi S. Ragarl" },
	{ "志津香２／", "Masou Shizuka" },
	{ "ドッス２／", "Doss" },
	{ "ワッス２／", "Wass" },
	{ "ウズメ２／", "Kentou Uzume" },
	{ "深根２／", "Tokugawa Fukane" },
	{ "ミックス２／", "Mix Toh" },
	{ "スシヌ２／", "Sushinu the Gandhi" },
	{ "レリコフ２／", "Rerikov Helman" },
	{ "元就２／", "Mouri Motonari" },
	{ "ダークランス２／", "Dark Rance" },
	{ "マリア２／", "Maria Custard" },
	{ "ランスＪｒ／", "Rance Jr." },
	{ "ドギ２／", "Doggy Magi" },
	{ "アームズ２／", "Arms Arc" },
	{ "マジック２／", "Magic the Gandhi" },
	{ "シーラ２／", "Sheila Hellman" },
	{ "リア２／", "Lia Parapara Leazas" },
	{ "ミラクル２／", "Miracle Toh" },
	{ "ビスケッタ２／", "Bisketta Bernes" },
	{ "コパンドン２／", "Copandon Dot" },
	{ "ヌーク７７２／", "Nuke77" },
	{ "香姫２／", "Oda Kaoru" },
	{ "タイガー将軍２／", "General Tiger" },
	{ "ランス２／", "Demon King Rance" },
	{ "リズナ２／", "Lizzna Lanfbitt" },
	{ "すず２／", "Hojo Suzu" },
	{ "早雲２／", "Hojo Soun" },
	{ "シュリ２／", "Shuri Seihajuu Nagasaki" },
	{ "ケイブリス２／", "K-chan" },
	{ "アレキサンダー２／", "Alexander" },
	{ "魔人ＤＤ／", "DD" },
	{ "魔女リクチェル／", "Rikucher von de Coesus" },
	{ "バイタル／", "Vital Fit" },
	{ "ドギ／", "Doggy Magi" },
	{ "汎用売春宿ボーイ／", "Brothel Boy" },
	{ "モロミ／", "Megadeath Moromi" },
	{ "セスナ／", "Cessna Benbier" },
	{ "プリマ／", "Prima Hononoman" }
};