/**
 * Find the race names the enemy status panel shows, and which number each one
 * answers to.
 *
 *   npm run regenerate-race-names
 *
 * An enemy's race is an int -- ▲種族 in Ｔ敵本体生成 -- and 表示種族 turns it
 * into the word the panel prints, as a run of twenty compares:
 *
 *     .LOCALREF aa / PUSH <number> / EQUALE / IFNZ / JUMP / S_PUSH <slot> / RETURN
 *
 * The numbers are what the .jaf that translates this has to switch on, and they
 * are nowhere but in that code, so this reads them out of it. See
 * modules/RaceNames.js for why the translation is a .jaf rather than the
 * twenty string slots, and docs/race-names.md for the whole of it.
 */
import * as fs from "fs/promises";
import * as os from "os";
import * as path from "path";
import * as readline from "readline";
import {createReadStream} from "fs";
import {AIN, AIN_TXT} from "../modules/AinFiles.js";
import {alice, run} from "../modules/AliceTools.js";
import {ROOT} from "../modules/Env.js";
import {readAinStrings} from "../modules/EnemyInfo.js";
import {RACE_FUNCTION, RACE_NAMES} from "../modules/RaceNames.js";

/**
 * The int-to-slot pairs in one function of the code dump.
 *
 * Every compare in there is against the one argument and answered by returning
 * one literal, so remembering the number the last EQUALE tested and reading it
 * off at the next S_PUSH is enough. The function ends with a bare S_PUSH of the
 * empty string -- the fallthrough -- which is left out by having nothing
 * pending to pair it with.
 */
const scanFunction = async (dumpPath, functionName) => {
    const pairs = [];
    let inComment = false;
    let inFunction = false;
    let seenName = false;
    let lastPushed = null;
    let pendingNumber = null;
    const input = createReadStream(dumpPath);
    for await (const line of readline.createInterface({input, crlfDelay: Infinity})) {
        if (line.startsWith("; ")) {
            if (!inComment) {
                seenName = line.slice(2) === functionName;
            }
            inComment = true;
            continue;
        }
        inComment = false;
        if (line.startsWith("FUNC ")) {
            inFunction = seenName;
            continue;
        }
        if (!inFunction) {
            continue;
        }
        if (line.startsWith("ENDFUNC")) {
            break;
        }
        const match = line.match(/^0x[0-9A-F]+:\s+(.*)$/);
        if (!match) {
            continue;
        }
        const instruction = match[1].trim();
        const pushed = instruction.match(/^PUSH 0x([0-9a-f]+)$/);
        if (pushed) {
            lastPushed = parseInt(pushed[1], 16);
        } else if (instruction === "EQUALE") {
            pendingNumber = lastPushed;
        } else {
            const string = instruction.match(/^S_PUSH 0x([0-9a-f]+)$/);
            if (string && pendingNumber !== null) {
                pairs.push({number: pendingNumber, slot: parseInt(string[1], 16)});
                pendingNumber = null;
            }
        }
    }
    if (!pairs.length) {
        throw new Error(`${functionName} is not in ${AIN}, or no longer decides anything by comparing`
            + ` its argument. The race names are somewhere else in this version.`);
    }
    return pairs;
};

run(async () => {
    const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "rance10-race-names-"));
    const codeDump = path.join(tempDir, "code.jam");
    try {
        const status = alice(["ain", "dump", "-C", "--no-macros", "-o", codeDump, AIN]);
        if (status !== 0) {
            return status;
        }
        const pairs = await scanFunction(codeDump, RACE_FUNCTION);
        const strings = await readAinStrings(AIN_TXT);

        const header = [
            `# The races the enemy status panel shows, as ${RACE_FUNCTION} decides them.`,
            "# Generated by scripts/extract_race_names.js -- edit glossaries/race_name_glossary.tsv",
            "# to change the English, not this file.",
            "#",
            "# Columns: the number ▲種族 holds <TAB> the Japanese, JSON-quoted <TAB> its string slot.",
            "# The slot is here to be read, not used: translating it is what the .jaf exists",
            "# to avoid, since six of these words are also something else somewhere.",
            "",
        ].join("\n");
        const rows = pairs
            .sort((a, b) => a.number - b.number)
            .map(({number, slot}) => `${number}\t${JSON.stringify(strings.get(slot) ?? "")}\t${slot}`);
        await fs.writeFile(RACE_NAMES, header + rows.join("\n") + "\n", "utf-8");

        console.log(`Found ${rows.length} races in ${RACE_FUNCTION}`
            + ` -> ${path.relative(ROOT, RACE_NAMES)}`);
        return 0;
    } finally {
        await fs.rm(tempDir, {recursive: true, force: true});
    }
});
