table 立ち絵名札マッピング情報 = {
	{ indexed string stand, string name },
	{ "アーシー／", "Arcy Julietta" },
	{ "アームズ／", "Arms Arc" },
	{ "アールコート／", "Arlcoate Marius" },
	{ "アギレダ", "Agireda Kosabusshi Zonna Abona" },
	{ "アスカ／", "Asuka Cadmium" },
	{ "アタゴ", "Atago McCart" },
	{ "アトランタ／", "Atlanta" },
	{ "アナセル／", "Anasel Caspora" },
	{ "アニス／", "Anise Sawatari" },
	{ "アミトス／", "Amitos Armitage" },
	{ "アム／", "Am Yisael" },
	{ "アルカネーゼ／", "Alkanese Rize" },
	{ "アルカリア／", "Alcarria" },
	{ "アレックス／", "Alex Valse" },
	{ "アレフガルド／", "Alefgard" },
	{ "イアン／", "Ian Ruston" },
	{ "イージス／", "Aegis Kalar" },
	{ "イオ／", "Io Ishtar" },
	{ "イカンティ／", "Ikanti Kalar" },
	{ "ウィチタ／", "Wichita Skate" },
	{ "ウィリス／", "Willis Fujisaki" },
	{ "ウェンリーナー小／", "Wenlina" },
	{ "ウェンリーナー大／", "Wenlina" },
	{ "ウスピラ／", "Uspira Shintou" },
	{ "ウルザ／", "Urza Pranaice" },
	{ "エクス／", "Ex Banquet" },
	{ "エルシール／", "Elsill" },
	{ "エレナ／", "Elena Flower" },
	{ "エレノア／", "Eleanor Ran" },
	{ "エロピチャ／", "Eropicha Nyanko" },
	{ "オーロラ／", "Aurora" },
	{ "オノハ／", "Onoha Mespos" },
	{ "オルオレ／", "Oruore the 3rd" },
	{ "カオス／", "Chaos" },
	{ "カオル／", "Kaoru Quincy Kagura" },
	{ "カスミ／", "Kasumi K. Kasumi" },
	{ "カチューシャ／", "Katyusha Bosch" },
	{ "少女カチューシャ", "Katyusha Bosch" },
	{ "かなみ／", "Kanami Kentou" },
	{ "カバッハーン／", "Kabachahn the Lightning" },
	{ "カフェ／", "Cafe Artful" },
	{ "カミーラ／", "Camilla" },
	{ "ガルティア／", "Galtia" },
	{ "カロリア／", "Caloria Cricket" },
	{ "ガンジー／", "Ragnarokarc Super Gandhi" },
	{ "きく／", "Kikkawa Kiku" },
	{ "キムチ／", "Kimchi Drive" },
	{ "キャロリ／", "Calory Mate" },
	{ "キラトーキ／", "Kiratouki" },
	{ "キンケード／", "Kinkaid Brambla" },
	{ "クリーム／", "Cream Ganoblade" },
	{ "クリン／", "Klean Bew" },
	{ "クルーチェ／", "Krutche Muffin" },
	{ "クルックー／", "Crook Mofus" },
	{ "クレイン／", "Crane" },
	{ "ケイコ／", "Keiko" },
	{ "ケイブニャン／", "Kaybnyan" },
	{ "ケイブリス／", "Kayblis" },
	{ "ケイブワン／", "Kaybwan" },
	{ "ケッセルリンク／", "Kesselring" },
	{ "コパンドン／", "Copandon Dott" },
	{ "コルドバ／", "Cordoba Burn" },
	{ "コンバート／", "Convert Tax" },
	{ "サーナキア／", "Sanakia Drelshkaf" },
	{ "サイアス／", "Saias Crown" },
	{ "サイゼル／", "La Saizel" },
	{ "サクラ／", "Sakura Kalar" },
	{ "サチコ／", "Sachiko Centers" },
	{ "サテラ／", "Satella" },
	{ "サメザン／", "Samezan" },
	{ "ジーク／", "Sieg" },
	{ "シーラ／", "Sheila Helman" },
	{ "シィル／", "Sill Plain" },
	{ "ジャロ／", "Jaro Jaslak" },
	{ "シャロン／", "Sharon" },
	{ "ジュノー／", "Juno" },
	{ "ジュリア／", "Julia Lindum" },
	{ "シルキィ／", "Silky Littleraisin" },
	{ "スー／", "Sioux Provence" },
	{ "セシル／", "Cecil Carna" },
	{ "セラクロラス小／", "Serachrolas" },
	{ "セラクロラス大／", "Serachrolas" },
	{ "セル／", "Sel Catchgolf" },
	{ "タルゴ／", "Thalgo" },
	{ "ちぬ／", "Chinu Kobayakawa" },
	{ "チャカ／", "Chaka Cadmium" },
	{ "チョチョマン／", "Chochoman Publy" },
	{ "チルディ／", "Tilde Sharp" },
	{ "テオマン／", "Arios Theoman" },
	{ "テラ／", "Terra Horus" },
	{ "てる／", "Mouri Teru" },
	{ "ニミッツ／", "Nimitz Leak" },
	{ "ニミッツレキシントン２／基本／", "Nimitz Leak" },
	{ "ニミッツレキシントン２／心の声／", "Nimitz Leak" },
	{ "ヌヌハラ／", "Nunuhara Cabbage" },
	{ "ネプラカス本体／", "Neplacus" },
	{ "ネルソン／", "Nelson Server" },
	{ "ノア／", "Noah Hakobune" },
	{ "ノーマルホルス／", "Horus" },
	{ "バード／", "Bird Lithfie" },
	{ "バーナード／", "Bernard Seramite" },
	{ "バーバラ／", "Barbara" },
	{ "パイアール／", "Pi-R" },
	{ "パイアールロボ／", "Pi-R" },
	{ "ハイジ／", "Heidi Pankrau" },
	{ "ハウセスナース小／", "Housesnurse" },
	{ "ハウセスナース大／", "Housesnurse" },
	{ "ハウゼル／", "La Hawzel" },
	{ "ハウレーン／", "Haurein Province" },
	{ "パステル／", "Pastel Kalar" },
	{ "バスワルド／", "La Vaswald" },
	{ "パセリ／", "Parsley Rig Zeth" },
	{ "パセリ幽霊／", "Parsley Rig Zeth" },
	{ "パットン／", "Patton Helman" },
	{ "パトリシア／", "Patricia Bacon" },
	{ "パパイア／", "Papaya Server" },
	{ "パパデマス／", "Papademas Shirusven" },
	{ "バボラ／", "Babolat" },
	{ "バレス／", "Barres Province" },
	{ "パレロア／", "Paleloa" },
	{ "ハンティ／", "Hunty Kalar" },
	{ "ピグ／", "Pigu Geliciam" },
	{ "ビスケッタ／", "Biscuitta Burns" },
	{ "ピッテン／", "Pitten Chao" },
	{ "ビビッド／", "Vivid Kalar" },
	{ "ビビッド幽霊／", "Vivid Kalar" },
	{ "ヒューバート／", "Hubert Lipton" },
	{ "ビヨンホウ／", "Villenhowe Osman" },
	{ "ファーレン／", "Varen" },
	{ "フル／", "Full Kalar" },
	{ "フル幽霊／", "Full Kalar" },
	{ "フレイア／", "Freya Idun" },
	{ "ペスポ／", "Pespo Tontone" },
	{ "ベゼルアイ小／", "Bezeleye" },
	{ "ベゼルアイ大／", "Bezeleye" },
	{ "ペルエレ／", "Peruele Kalette" },
	{ "ホーネット／", "Hornet" },
	{ "ポロン／", "Poron Chao" },
	{ "マーシー／", "Mercy Julietta" },
	{ "マジック／", "Magic the Gandhi" },
	{ "ますぞえ／", "Masuzoe" },
	{ "マリア／", "Maria Custard" },
	{ "マリス／", "Maris Amaryllis" },
	{ "マルチナ／", "Martina Curry" },
	{ "ミステリア／", "Mysteria Tou" },
	{ "ミラクル／", "Miracle Tor" },
	{ "ミル／", "Mill Yorks" },
	{ "メアリー／", "Mary Ann" },
	{ "メアリー２／", "Mary Ann" },
	{ "メイドロナ／", "Rona Kestina" },
	{ "メガッス／", "Megas Horus" },
	{ "メガフォース／", "Megaforce Horus" },
	{ "メガワス／", "Megawas Horus" },
	{ "メディウサ／", "Medusa" },
	{ "メナド／", "Menad Shisei" },
	{ "メリム／", "Merim Tser" },
	{ "メルフェイス／", "Melfeis Promenade" },
	{ "モダン／", "Modern Kalar" },
	{ "モダン幽霊／", "Modern Kalar" },
	{ "ユーティン／", "Yutin Fulz" },
	{ "ユキ／", "Yuki" },
	{ "ラウネア／", "Launea" },
	{ "ラッシー／", "Lassie" },
	{ "リア／", "Lia Parapara Leazas" },
	{ "リズナ／", "Rizna Lanfbitt" },
	{ "リセット／", "Reset Kalar" },
	{ "リック／", "Rick Addison" },
	{ "リトルプリンセス／", "Demon King Little Princess" },
	{ "リリム／", "Lilim" },
	{ "ルーシー／", "Lucy Julietta" },
	{ "ルート／", "Root Ari" },
	{ "ルート肉片／", "Meat Chunk" },
	{ "ルーベラン／", "Ruberan Tser" },
	{ "レイ／", "Lei" },
	{ "レイラ／", "Leila Gurekuni" },
	{ "レキシントン２／", "Lexington" },
	{ "レッドアイアニス／", "RedEye" },
	{ "レッドアイトッポス／", "RedEye" },
	{ "レッドアイ魔法魔物兵／", "RedEye" },
	{ "ロードリング／", "Mi Lordring" },
	{ "ロッキー／", "Rocky Bank" },
	{ "ロナ／", "Rona Kestina" },
	{ "ロレックス／", "Rolex Gadras" },
	{ "ワーグ／", "Warg" },
	{ "香姫", "Oda Kouhime" },
	{ "愛／", "Naoe Ai" },
	{ "加奈代／", "Kanayo" },
	{ "火炎書士／", "Flame Scrivener" },
	{ "花屋エレナ／", "Elena Flower" },
	{ "健太郎／", "Ogawa Kentarou" },
	{ "謙信／", "Uesugi Kenshin" },
	{ "虎子／", "Uesugi Torako" },
	{ "五十六／", "Yamamoto Isoroku" },
	{ "子供ナギ／", "Nagi su Ragarl" },
	{ "子供志津香／", "Masou Shizuka" },
	{ "子供志津香とナギ／", "Shizuka and Nagi" },
	{ "篠田源五郎／", "Shinoda Gengorou" },
	{ "女ケッセルリンク／", "Kesselring" },
	{ "勝子／", "Uesugi Katsuko" },
	{ "政宗／", "Dokuganryuu Masamune" },
	{ "千鶴子／", "Yamada Chizuko" },
	{ "千姫／", "Tokugawa Sen" },
	{ "早雲／", "Houjou Souun" },
	{ "朝倉義景／", "Asakura Yoshikage" },
	{ "超人アギレダ／", "Agireda Kosabusshi Zonna Abona" },
	{ "透琳／", "Sanada Tourin" },
	{ "日光刀／", "Nikkou" },
	{ "日立姫／", "Princess Hitachi" },
	{ "日立姫砂漠案内人／", "Desert Guide" },
	{ "汎用カラー／", "Kalar" },
	{ "汎用グリーンハニー／", "Green Hanny" },
	{ "汎用ゼス女魔法兵／", "Zeth Mage Soldier" },
	{ "汎用ゼス男魔法兵／", "Zeth Mage Soldier" },
	{ "汎用テンプルナイト／", "Temple Knight" },
	{ "汎用ハニー／", "Hanny" },
	{ "汎用ブラックハニー／", "Black Hanny" },
	{ "汎用ブルーハニー／", "Blue Hanny" },
	{ "汎用ヘルマン騎士／", "Helman Knight" },
	{ "汎用ヘルマン兵／", "Helman Soldier" },
	{ "汎用ランス城騎士／", "Rance Castle Knight" },
	{ "汎用リーザス黒騎士／", "Leazas Black Knight" },
	{ "汎用リーザス黒兵／", "Leazas Black Soldier" },
	{ "汎用リーザス親衛隊／", "Leazas Royal Guard" },
	{ "汎用リーザス青騎士／", "Leazas Blue Knight" },
	{ "汎用リーザス青兵／", "Leazas Blue Soldier" },
	{ "汎用リーザス赤騎士／", "Leazas Red Knight" },
	{ "汎用リーザス赤兵／", "Leazas Red Soldier" },
	{ "汎用リーザス白騎士／", "Leazas White Knight" },
	{ "汎用リーザス白兵／", "Leazas White Soldier" },
	{ "汎用レッドハニー／", "Red Hanny" },
	{ "汎用筋肉男／", "Muscle Man" },
	{ "汎用穴奴隷／", "Sex Slave" },
	{ "汎用自由都市警備兵Ａ／", "Free Cities Guard" },
	{ "汎用自由都市警備兵Ｂ／", "Free Cities Guard" },
	{ "汎用女／", "Woman" },
	{ "汎用女ポピンズ１／", "Poppins" },
	{ "汎用女ポピンズ２／", "Poppins" },
	{ "汎用女武士兵／", "JAPAN Samurai" },
	{ "汎用少女／", "Girl" },
	{ "汎用少年／", "Boy" },
	{ "汎用男／", "Man" },
	{ "汎用男ポピンズ１／", "Poppins" },
	{ "汎用男ポピンズ２／", "Poppins" },
	{ "汎用男武士兵／", "JAPAN Samurai" },
	{ "汎用天使／", "Angel" },
	{ "汎用闘将Ａ／", "Battle General" },
	{ "汎用闘将Ｂ／", "Battle General" },
	{ "汎用闘将Ｃ／", "Battle General" },
	{ "汎用婆／", "Old Woman" },
	{ "汎用飛行魔物兵／", "Flying Monster Soldier" },
	{ "汎用武将／", "JAPAN General" },
	{ "汎用魔物使い／", "Monster Tamer" },
	{ "汎用魔物将軍／", "Monster General" },
	{ "汎用魔物隊長／", "Monster Captain" },
	{ "汎用魔物兵青／", "Blue Monster Soldier" },
	{ "汎用魔物兵赤／", "Red Monster Soldier" },
	{ "汎用魔物兵緑／", "Green Monster Soldier" },
	{ "汎用魔法魔物兵／", "Magic Monster Soldier" },
	{ "汎用爺／", "Old Man" },
	{ "汎用巫女／", "Miko" },
	{ "美樹／", "Kurusu Miki" },
	{ "柚美／", "Yuzuhara Yuzumi" },
	{ "女神アリス／", "Goddess ALICE" },
	{ "エロヤック／", "Eroyack ALV" },
	{ "海獣レイド／", "Kaiju Raidboss" },
	{ "汎用弓兵／", "Archer" },
	{ "汎用戦士／", "Warrior" },
	{ "汎用東ヘルマン兵／", "East Helman Soldier" },
	{ "汎用魔法使い／", "Wizard" },
	{ "大地の次世代魔物／", "Hanman" },
	{ "命の次世代魔物／", "Kiba-o" },
	{ "力の次世代魔物／", "Kill Kill Tak" },
	{ "時の次世代魔物／", "White Satan" },
	{ "アマデス／", "Amades Kakades" },
	{ "オーギル／", "Ogier Lott Stein" },
	{ "ニーナ／", "Nina Nirvana" },
	{ "シルバレル／", "Silbarrel Silbarella" },
	{ "ドエススキー／", "Don Doessky" },
	{ "トルストイ／", "Tolstoy Bato" },
	{ "アカシロ／", "Akashiro Kalar" },
	{ "イベット／", "Yvette Cheria" },
	{ "サムソン／", "Samson Maximov" },
	{ "デストラー／", "Bintan Destora" },
	{ "エール２／", "El Mofus" },
	{ "クルックー２／", "Crook Mofus" },
	{ "乱義２／", "Yamamoto Rangi" },
	{ "ザンス２／", "Zance Leazas" },
	{ "ヒーロー２／", "Hero Helman" },
	{ "長田君２／", "Nagata-kun" },
	{ "ロッキー２／", "Rocky Bank" },
	{ "リセット２／", "Reset Kalar" },
	{ "ナギ２／", "Nagi su Ragarl" },
	{ "志津香２／", "Masou Shizuka" },
	{ "ドッス２／", "Doss" },
	{ "ワッス２／", "Wass" },
	{ "ウズメ２／", "Kentou Uzume" },
	{ "深根２／", "Tokugawa Tone" },
	{ "ミックス２／", "Mix Tou" },
	{ "スシヌ２／", "Sushinu the Gandhi" },
	{ "レリコフ２／", "Lelikov Helman" },
	{ "元就２／", "Mouri Motonari" },
	{ "ダークランス２／", "Dark Rance" },
	{ "マリア２／", "Maria Custard" },
	{ "ランスＪｒ／", "Rance Jr." },
	{ "ドギ２／", "Dogi Magi" },
	{ "アームズ２／", "Arms Arc" },
	{ "マジック２／", "Magic the Gandhi" },
	{ "シーラ２／", "Sheila Helman" },
	{ "リア２／", "Lia Parapara Leazas" },
	{ "ミラクル２／", "Miracle Tor" },
	{ "ビスケッタ２／", "Biscuitta Burns" },
	{ "コパンドン２／", "Copandon Dott" },
	{ "ヌーク７７２／", "Nook 77" },
	{ "香姫２／", "Oda Kouhime" },
	{ "タイガー将軍２／", "General Tiger" },
	{ "ランス２／", "Demon King Rance" },
	{ "リズナ２／", "Rizna Lanfbitt" },
	{ "すず２／", "Houjou Suzu" },
	{ "早雲２／", "Houjou Souun" },
	{ "シュリ２／", "Shuri Seihajuu Nagasaki" },
	{ "ケイブリス２／", "K-Chan" },
	{ "アレキサンダー２／", "Alexander" },
	{ "魔人ＤＤ／", "DD" },
	{ "魔女リクチェル／", "Richelle von do Kosusu" },
	{ "バイタル／", "Vital Fit" },
	{ "ドギ／", "Dogi Magi" },
	{ "汎用売春宿ボーイ／", "Brothel Boy" },
	{ "モロミ／", "Megadeath Moromi" },
	{ "セスナ／", "Cessna Benville" },
	{ "プリマ／", "Prima Hononoman" }
	{ "ストロガノフ／", "Stroganoff" },
	{ "マッスル／", "Muscle" },
	{ "学者／", "Scholar" },
	{ "シーザ／", "Caesar" },
	{ "迷宮の声／", "Voice of the Labyrinth" },
	{ "赤ん坊の泣き声／", "Baby crying" },
	{ "ベゼルアイ／", "Bezeleye" },
	{ "ウェンリーナー／", "Wenlina" },
	{ "闇鷺／", "Yamisagi" },
	{ "茶屋の娘／", "Tea house girl" },
	{ "シャリエラ／", "Shariela" },
	{ "魂管理局クエルプラン／", "Quelplan" },
	{ "日光／", "Nikkou" },
	{ "大将軍ルメイ／", "LeMay" },
	{ "大将軍ヨシフ／", "Joseph" },
	{ "ランス城／", "Rance" },
	{ "セラクロラス／", "Serachrolas" },
	{ "大将軍ピサロ／", "Pizarro" },
	{ "ダークランス／", "Rance" },
	{ "ハニーキング／", "Hanny" },
	{ "大将軍ツォトン／", "Zedong" },
	{ "レッドアイ／", "RedEye" },
	{ "魔王ケイブリス／", "Kayblis" },
	{ "プルーペット／", "Pluepet" },
	{ "ザカリテ／", "Xacalite" },
	{ "アリオス／", "Arios" },
	{ "ランスの部屋／", "Rance" },
	{ "ハウセスナースの恋人／", "Housesnurse" },
	{ "魔物将軍マックス／", "Monster General" },
	{ "リーザス平原／", "Leazas" },
	{ "クエルプラン／", "Quelplan" },
	{ "ヘルマン平原／", "Helman" },
	{ "自由都市平原／", "Free Cities" },
	{ "魔物将軍グスマン／", "Monster General" },
	{ "ハニーＡ／", "Hanny" },
	{ "リーザス城／", "Leazas" },
	{ "魔物将軍ポル／", "Monster General" },
	{ "物知りハニー／", "Hanny" },
	{ "ゼス兵Ａ／", "Zeth" },
	{ "山田千鶴子／", "Yamada Chizuko" },
	{ "ハニーＢ／", "Hanny" },
	{ "ゼス平原／", "Zeth" },
	{ "柔らかマニアハニー／", "Hanny" },
	{ "魔物将軍Ｂ／", "Monster General" },
	{ "ジフテリア兵／", "Diphteria" },
	{ "魔物将軍Ａ／", "Monster General" },
	{ "ヘルマン都市／", "Helman" },
	{ "空飛ぶランス城／", "Rance" },
	{ "フィッシングハニー／", "Hanny" },
	{ "自由都市連合軍兵士／", "Free Cities" },
	{ "自由都市の王／", "Free Cities" },
	{ "魔物将軍Ｃ／", "Monster General" },
	{ "ゼス都市／", "Zeth" },
	{ "ゼス迷宮／", "Zeth" },
	{ "ハウセスナース／", "Housesnurse" },
	{ "魔軍司令部内／", "Monster Army" },
	{ "リーザス城内／", "Leazas" },
	{ "ゼス士官／", "Zeth" },
	{ "魔軍野営地／", "Monster Army" },
	{ "変身魔人？／", "Fiend" },
	{ "ゼス最強魔法使い(レッドアイに寄生され中)／", "RedEye" },
	{ "求めるハニー／", "Hanny" },
	{ "ハニー／", "Hanny" },
	{ "ランスの？？？／", "Rance" },
	{ "ヘルマン村／", "Helman" },
	{ "ランス砦／", "Rance" },
	{ "クエルプラン体内／", "Quelplan" },
	{ "リーザス兵マポンタ／", "Leazas" },
	{ "氷溶のハニー／", "Hanny" },
	{ "魔物将軍バルボア／", "Monster General" },
	{ "小ピグ／", "Pigu Geliciam" },
	{ "ランス城飛ぶ／", "Rance" },
	{ "幼い虎子／", "Uesugi Torako" },
	{ "ヘルマンの男性／", "Helman" },
	{ "リーザス騎士ガモリ／", "Leazas" },
	{ "上訴ハニー／", "Hanny" },
	{ "ハニー隊長／", "Hanny" },
	{ "魔物将軍コルテス／", "Monster General" },
	{ "新聞勧誘魔人／", "Fiend" },
	{ "巨大ピグ・ギリシアム／", "Pigu Geliciam" },
	{ "リーザスの貴族／", "Leazas" },
	{ "ゼス兵Ｂ／", "Zeth" },
	{ "自由都市兵士Ｃ／", "Free Cities" },
	{ "ゼス村／", "Zeth" },
	{ "ゼス城／", "Zeth" },
	{ "カラーの村／", "Kalar" },
	{ "偽ランス／", "Rance" },
	{ "ゼス市民／", "Zeth" },
	{ "魔軍野戦テント／", "Monster Army" },
	{ "魔物将軍／", "Monster General" },
	{ "ランス船団／", "Rance" },
	{ "ゼス民／", "Zeth" },
	{ "魔物将軍ムレレ／", "Monster General" },
	{ "ゼス３の移動先／", "Zeth" },
	{ "自由都市連合軍隊員／", "Free Cities" },
	{ "自由都市軍兵士／", "Free Cities" },
	{ "魔物大将軍ピサロ？／", "Pizarro" },
	{ "自由都市連合兵士／", "Free Cities" },
	{ "ランスの寝息／", "Rance" },
	{ "ゼスの高官／", "Zeth" },
	{ "ゼス市民Ａ／", "Zeth" },
	{ "ゼス市民Ｂ／", "Zeth" },
	{ "ランス？／", "Rance" },
	{ "ゼス兵？／", "Zeth" },
	{ "リーザス兵／", "Leazas" },
	{ "ラストガンジー／", "Ragnarokarc Super Gandhi" },
	{ "はらぺこハニー／", "Hanny" },
	{ "まわしハニー／", "Hanny" },
	{ "魔軍の下僕／", "Monster Army" },
	{ "魔物将軍ソト／", "Monster General" },
	{ "魔物将軍カサス／", "Monster General" },
	{ "風船ピグ／", "Pigu Geliciam" },
	{ "対象はリーザス／", "Leazas" },
	{ "対象はヘルマン／", "Helman" },
	{ "対象はゼス／", "Zeth" },
	{ "ランス達の逃亡先／", "Rance" },
	{ "ヘルマンの貴族／", "Helman" },
	{ "自由都市の政治家／", "Free Cities" },
	{ "遠くのアナセルの声／", "Anasel Caspora" },
	{ "ヘルマンの女性／", "Helman" },
	{ "シャリエラのエロ／", "Shariela" },
	{ "ゼス城内／", "Zeth" },
	{ "対象は自由都市／", "Free Cities" },
	{ "ナレーターハニー／", "Hanny" },
	{ "ハニー達／", "Hanny" },
	{ "今川ハニー／", "Hanny" },
	{ "ヘルマン騎士トッパル／", "Helman" },
	{ "左ガンジー／", "Ragnarokarc Super Gandhi" },
	{ "右ガンジー／", "Ragnarokarc Super Gandhi" },
	{ "真ん中ガンジー／", "Ragnarokarc Super Gandhi" },
	{ "ゼス情報官／", "Zeth" },
	{ "女ポピンズ／", "Poppins" },
	{ "自由都市連合兵／", "Free Cities" },
	{ "自由都市健在／", "Free Cities" },
	{ "リーザスの老人／", "Leazas" },
	{ "ヘルマンの少年／", "Helman" },
	{ "ゼスの男／", "Zeth" },
	{ "踊るハニー／", "Hanny" },
	{ "ご機嫌なハニー／", "Hanny" },
	{ "歌うハニー／", "Hanny" },
	{ "転がるハニー／", "Hanny" },
	{ "跳ねるハニー／", "Hanny" },
	{ "胸張るハニー／", "Hanny" },
	{ "かしげるハニー／", "Hanny" },
	{ "鳴くハニー／", "Hanny" },
	{ "プチハニー／", "Hanny" },
	{ "ランスの声／", "Rance" },
	{ "魔物将軍たち／", "Monster General" },
	{ "ピサロハニー／", "Pizarro" },
	{ "連合軍総隊長セシル／", "Cecil Carna" },
	{ "ランスの寝言／", "Rance" },
	{ "ハニーフラッシュ／", "Hanny" },
	{ "ランス城周辺／", "Rance" },
	{ "ヘルマンの領主／", "Helman" },
	{ "ゼスの政治家／", "Zeth" },
	{ "ヘルマン兵達／", "Helman" },
	{ "魔物に陵辱されるシルキィ／", "Silky Littleraisin" },
	{ "リーザス兵達／", "Leazas" },
	{ "進撃のテオマン／", "Arios Theoman" },
	{ "クエルプランのエロ／", "Quelplan" },
	{ "魔王ランスとシィル／", "Sill Plain" },
	{ "自由都市１／", "Free Cities" },
	{ "自由都市方面／", "Free Cities" },
	{ "親友リセット／", "Reset Kalar" },
	{ "親友ザンス／", "Zance" },
	{ "親友深根／", "Tone" },
	{ "親友ダークランス／", "Rance" },
	{ "ゼス市民Ｃ／", "Zeth" },
	{ "ゼス町民Ａ／", "Zeth" },
	{ "ゼス町民Ｂ／", "Zeth" },
	{ "ゼス町民Ｃ／", "Zeth" },
	{ "ゼス町民Ｄ／", "Zeth" },
	{ "ゼス市民A／", "Zeth" },
	{ "ゼス市民B／", "Zeth" },
	{ "ハニーA／", "Hanny" },
	{ "ハニーB／", "Hanny" },
	{ "見物ハニーＡ／", "Hanny" },
	{ "見物ハニーＢ／", "Hanny" },
	{ "見物ハニーＣ／", "Hanny" },
	{ "見物ハニーＤ／", "Hanny" },
	{ "見物ハニーＥ／", "Hanny" },
	{ "見物ハニーＦ／", "Hanny" },
	{ "見物ハニーＧ／", "Hanny" },
	{ "ゼス兵Ｃ／", "Zeth" },
	{ "自由都市軍兵士Ａ／", "Free Cities" },
	{ "自由都市軍兵士Ｂ／", "Free Cities" },
	{ "自由都市連合軍兵士Ａ／", "Free Cities" },
	{ "自由都市連合軍兵士Ｂ／", "Free Cities" },
	{ "自由都市兵士Ｄ／", "Free Cities" },
	{ "汎用その他／", "Generic Other" },
	{ "フェリス／", "Feris" },
	{ "コーラ／", "Cola" },
	{ "東芝王子／", "Prince Toshiba" },
	{ "あてな２号／", "Athena 2.0" },
	{ "松下姫／", "Princess Matsushita" },
	{ "裸族王バファムーン／", "Bafamoon, King of the Naked Tribe" },
	{ "折女／", "Orime" },
	{ "黒部／", "Kurobe" },
	{ "お町／", "Omachi" },
	{ "ホ・ラガ／", "Ho Laga" },
	{ "フィールド／", "Field" },
	{ "野菊／", "Nogiku" },
	{ "乳久里／", "Chikuri" },
	{ "ノワール／", "Noir" },
	{ "タイガー将軍／", "Tiger General" },
	{ "鈴女／", "Suzume" },
	{ "量産型あてな２号／", "Mass-produced Athena 2.0" },
	{ "あおい／", "Aoi" },
	{ "The Mysterious Beautiful Detective.", "The Mysterious Beautiful Detective." },
	{ "闘神シグマ／", "Fighting God Sigma" },
	{ "ミカン／", "Mikan" },
	{ "ハニ子／", "Haniko" },
	{ "キバ子／", "Kibako" },
	{ "ニードル／", "Needle" },
	{ "満鉄王／", "King Mantetsu" },
	{ "紀伊／", "Kii" },
	{ "Darson the Demon General", "Darson the Demon General" },
	{ "Bandit A", "Bandit A" },
	{ "三菱王／", "King Mitsubishi" },
	{ "キャンテル／", "Kanteru" },
	{ "戯骸／", "Gigai" },
	{ "タマ／", "Tama" },
	{ "アパッチ／", "Apache" },
	{ "闘神ゼータ／", "Fighting God Zeta" },
	{ "Lieutenant Alekozin", "Lieutenant Alekozin" },
	{ "Monster Captain Brobio", "Monster Captain Brobio" },
	{ "フロストバイン／", "Frostbain" },
	{ "ソルトアン／", "Sorutoan" },
	{ "船長／", "Captain" },
	{ "The mysterious girl", "The mysterious girl" },
	{ "ブリティシュ／", "British" },
	{ "エリザベート・デス／", "Elizabeth Death" },
	{ "泥姫バイランローズ／", "Mud Princess Bryanrose" },
	{ "Former Kayblis Faction Demon", "Former Kayblis Faction Demon" },
	{ "アリス／", "Alice" },
	{ "ネプラカス爺／", "Elder Neplacus" },
	{ "魔法／", "Magic" },
	{ "Bandit B", "Bandit B" },
	{ "青鬼／", "Blue Ogre" },
	{ "中島君／", "Nakajima-kun" },
	{ "赤鬼／", "Red Ogre" },
	{ "ＫＤ／", "KD" },
	{ "元船長／", "Former Captain" },
	{ "ヘケート／", "Hecate" },
	{ "剣豪／", "Master Swordsman" },
	{ "クゥ／", "Cu" },
	{ "トト村の村長／", "Toto Village Chief" },
	{ "イカマン／", "Squid Man" },
	{ "レキシントン／", "Lexington" },
	{ "王様／", "King" },
	{ "ブラックロータス／", "Black Lotus" },
	{ "リターンデーモン／", "Return Demon" },
	{ "アサシン集団の構成員／", "Assassin Group Member" },
	{ "村の長老／", "Village Elder" },
	{ "東芝王／", "King Toshiba" },
	{ "弥次さん／", "Yaji-san" },
	{ "いじめっ子のボロコフ／", "Borokov the Bully" },
	{ "調教師の男／", "Trainer Man" },
	{ "砂漠案内人／", "Desert Guide" },
	{ "一家の父／", "Father of the Family" },
	{ "老人／", "Old Man" },
	{ "田舎娘／", "Country Girl" },
	{ "Survivor of Dragon Kalar Race", "Survivor of Dragon Kalar Race" },
	{ "Innkeeper", "Innkeeper" },
	{ "マフィン家の執事／", "Muffin Family Butler" },
	{ "流動金属生命体／", "Liquid Metal Lifeform" },
	{ "魔物隊長アバシリ／", "Monster Captain Abashiri" },
	{ "喜多さん／", "Kita-san" },
	{ "アサシン集団の連絡役／", "Assassin Group Liaison" },
	{ "骸骨王モドカタ／", "Skeleton King Modokata" },
	{ "小隊長／", "Squad Leader" },
	{ "ジャハルッカス／", "Jaharukkasu" },
	{ "村人Ａ／", "Villager A" },
	{ "魔血魂／", "Demon Blood Soul" },
	{ "翔竜山／", "Mt. Shoryu" },
	{ "ベテラン売春婦／", "Veteran Prostitute" },
	{ "遙か高位の存在／", "A Being of Far Higher Rank" },
	{ "Bandit C", "Bandit C" },
	{ "側近闘将／", "Aide Battle General" },
	{ "山賊／", "Bandit" },
	{ "都市長／", "City Mayor" },
	{ "船大工／", "Shipwright" },
	{ "黄羅闘鬼-ｷﾗﾄｰｷ-／", "Kouratouki -Kiratouki-" },
	{ "少女／", "Girl" },
	{ "未亡人／", "Widow" },
	{ "ミカン星人／", "Mikan Alien" },
	{ "兵士Ａ／", "Soldier A" },
	{ "使者／", "Messenger" },
	{ "ヘクトミリバール・千津／", "Hectomillibar Chizu" },
	{ "ヌーク７７／", "Nook 77" },
	{ "魔獣タイガー／", "Beast Tiger" },
	{ "ラングバウ／", "Rangbau" },
	{ "魔物隊長／", "Monster Captain" },
	{ "起床係の魔物兵／", "Monster Soldier on Wake-up Duty" },
	{ "妖怪／", "Yokai" },
	{ "村長／", "Village Chief" },
	{ "ぶたバンバラ／", "Buta Banbara" },
	{ "Village Youth", "Village Youth" },
	{ "宝箱だんご／", "Treasure Chest Dango" },
	{ "炎軍隊長／", "Flame Army Captain" },
	{ "闇アリス／", "Dark Alice" },
	{ "一家の母／", "Mother of the Family" },
	{ "天使Ａ／", "Angel A" },
	{ "Entourage Haniko A", "Entourage Haniko A" },
	{ "茂雄／", "Shigeo" },
	{ "ハイレベル神(１０級神)／", "High-Level God (Rank 10 God)" },
	{ "アテナ／", "Athena" },
	{ "当主の老婆／", "Elderly Matriarch" },
	{ "アシュタルクー／", "Ashutaruku" },
	{ "勇者ゲイマルク／", "Hero Gaimark" },
	{ "通行人の男Ａ／", "Passerby Man A" },
	{ "Mrs. Marie", "Mrs. Marie" },
	{ "忠信／", "Tadanobu" },
	{ "ドラゴン／", "Dragon" },
	{ "防衛隊長／", "Defense Captain" },
	{ "眼鏡の奴隷娘／", "Bespectacled Slave Girl" },
	{ "手裏剣使い／", "Shuriken User" },
	{ "スパーン／", "Spahn" },
	{ "奴隷商人／", "Slave Merchant" },
	{ "逃げてきた中年男／", "Middle-Aged Man Who Fled" },
	{ "死国／", "Deathkoku" },
	{ "魔物兵Ａ／", "Monster Soldier A" },
	{ "Mランド／", "M Land" },
	{ "めぽら／", "Mepora" },
	{ "体育スター／", "Gym Star" },
	{ "ホルス／", "Horus" },
	{ "住民A／", "Resident A" },
	{ "トッポス／", "Toppos" },
	{ "伝令兵／", "Messenger Soldier" },
	{ "通信兵／", "Signal Soldier" },
	{ "男装女／", "Cross-dressing Woman" },
	{ "ガゴ村の村長／", "Chief of Gago Village" },
	{ "アスベスト／", "Asbestos" },
	{ "山賊たち／", "Bandits" },
	{ "金髪の奴隷娘／", "Blonde Slave Girl" },
	{ "てばさき伝令兵／", "Tebasaki Messenger Soldier" },
	{ "よーぜふ／", "Yosef" },
	{ "ガルバン／", "Galban" },
	{ "鉄腕ラブル／", "Iron Arm Rablu" },
	{ "強そうな男の子モンスター／", "Tough-Looking Boy Monster" },
	{ "巨大魔血魂／", "Giant Demon Blood Soul" },
	{ "メインキャスター／", "Main Caster" },
	{ "テンプルナイトＡ／", "Temple Knight A" },
	{ "兵士Ｂ／", "Soldier B" },
	{ "魔物兵Ｂ／", "Monster Soldier B" },
	{ "魔物兵Ｃ／", "Monster Soldier C" },
	{ "Guide Hanny", "Guide Hanny" },
	{ "DXの会　会員／", "DX Club Member" },
	{ "青軍隊長／", "Blue Army Captain" },
	{ "はいからちゃん／", "Haikara-chan" },
	{ "創造神／", "Creator God" },
	{ "ラプのみなし子／", "Rapu's Orphan" },
	{ "酒場のゴロツキ／", "Tavern Thug" },
	{ "通行人の男Ｂ／", "Passerby Man B" },
	{ "Merchant A", "Merchant A" },
	{ "Monster (Special Individual)", "Monster (Special Individual)" },
	{ "料理評論家モガロ／", "Food Critic Mogaro" },
	{ "フクノリ／", "Fukunori" },
	{ "母親／", "Mother" },
	{ "ガード隊長／", "Guard Captain" },
	{ "魔法隊長／", "Magic Captain" },
	{ "ナスティ／", "Nasty" },
	{ "女性士官／", "Female Officer" },
	{ "シャチ子／", "Shachiko" },
	{ "外宇宙の旧支配者（？）／", "The Old Ruler of Outer Space (?)" },
	{ "宇宙船／", "Spaceship" },
	{ "イカ帝国警備隊長／", "Squid Empire Guard Captain" },
	{ "司教マニカオ／", "Bishop Manikao" },
	{ "傭兵Ａ／", "Mercenary A" },
	{ "Old Lady at the Teahouse", "Old Lady at the Teahouse" },
	{ "Rance Faction Demon", "Rance Faction Demon" },
	{ "伝令／", "Messenger" },
	{ "チューリップ３号／", "Tulip No. 3" },
	{ "女性／", "Woman" },
	{ "ミリリッカ／", "Miririkka" },
	{ "ラブルム／", "Rablum" },
	{ "魔女ばあさん／", "Witch Granny" },
	{ "拘束された女性／", "Restrained Woman" },
	{ "雷軍兵士／", "Thunder Army Soldier" },
	{ "肥え太った男／", "Obese Man" },
	{ "傭兵／", "Mercenary" },
	{ "悪魔回廊／", "Demon Corridor" },
	{ "青髪の奴隷娘／", "Blue-Haired Slave Girl" },
	{ "スリの父親／", "The Pickpockets Father" },
	{ "浮浪者／", "Vagrant" },
	{ "ＩＰボディ／", "IP Body" },
	{ "ミイラン／", "Miiran" },
	{ "少年Ａ／", "Boy A" },
	{ "闘将Ｂ／", "Battle General B" },
	{ "伝令兵Ａ／", "Messenger Soldier A" },
	{ "奴隷娘Ａ／", "Slave Girl A" },
	{ "民家内／", "Private House" },
	{ "The man claiming to be the Demon King's son", "The man claiming to be the Demon Kings son" },
	{ "レベル神(１１級神)？／", "Level God (Rank 11 God)?" },
	{ "少女兵／", "Girl Soldier" },
	{ "少年／", "Boy" },
	{ "取り立て人／", "Debt Collector" },
	{ "兵馬俑／", "Terracotta Warrior" },
	{ "たくましい男／", "Sturdy Man" },
	{ "工場長ロボ／", "Factory Manager Robot" },
	{ "ぼうけんしゃ／", "Adventurer" },
	{ "パケット／", "Packet" },
	{ "ノートンガツ／", "Notongatsu" },
	{ "上野花子／", "Ueno Hanako" },
	{ "村の守り神様／", "Village Guardian God" },
	{ "アリス人形／", "Alice Doll" },
	{ "ドッヂ・エバンス／", "Dodge Evans" },
	{ "控え室／", "Waiting Room" },
	{ "闘将Ａ／", "Battle General A" },
	{ "闘将Ｃ／", "Battle General C" },
	{ "傭兵Ｂ／", "Mercenary B" },
	{ "棺の部屋／", "Coffin Room" },
	{ "Entourage Haniko B", "Entourage Haniko B" },
	{ "Entourage Haniko C", "Entourage Haniko C" },
	{ "Korra the talkative one", "Korra the talkative one" },
	{ "A fan of Reset", "A fan of Reset" },
	{ "Believer Naked", "Believer Naked" },
	{ "ドリル／", "Drill" },
	{ "電卓キューブ／", "Calculator Cube" },
	{ "氷軍部隊長／", "Ice Army Squad Captain" },
	{ "黒軍隊長／", "Black Army Captain" },
	{ "ブレイブ号／", "The Brave" },
	{ "兵士／", "Soldier" },
	{ "ボルチーニ／", "Borchini" },
	{ "アラーム／", "Alarm" },
	{ "石化した人／", "Petrified Person" },
	{ "地図／", "Map" },
	{ "副官／", "Adjutant" },
	{ "マント／", "Cloak" },
	{ "通行人／", "Passerby" },
	{ "花子／", "Hanako" },
	{ "乳久里の後輩巫女／", "Chikuris Junior Shrine Maiden" },
	{ "氷雪地帯案内人／", "Snow Region Guide" },
	{ "うし車／", "Ox Cart" },
	{ "コメンテーターの岸さん／", "Commentator Kishi-san" },
	{ "女の子／", "Girl" },
	{ "村長の妻／", "The Village Chiefs Wife" },
	{ "男性Ａ／", "Man A" },
	{ "老人Ａ／", "Old Man A" },
	{ "天使Ｂ／", "Angel B" },
	{ "ＹＯＲＡ／", "YORA" },
	{ "通行人の男Ｃ／", "Passerby Man C" },
	{ "マジノ要塞／", "Maginot Fortress" },
	{ "人工迷宮／", "Artificial Labyrinth" },
	{ "スルメ山／", "Mt. Surume" },
	{ "Apostle of Demon Barksham", "Apostle of Demon Barksham" },
	{ "Former monster commander.", "Former monster commander." },
	{ "A young mother", "A young mother" },
	{ "Former Jail Boss", "Former Jail Boss" },
	{ "Brobio's Partner", "Brobios Partner" },
	{ "暗殺者／", "Assassin" },
	{ "少女姿の密偵／", "Spy in a Girls Form" },
	{ "キャラ／", "Character" },
	{ "闘将たち／", "Battle Generals" },
	{ "魔物死体／", "Monster Corpse" },
	{ "囚われの女性／", "Captive Woman" },
	{ "毒鬼／", "Poison Ogre" },
	{ "お手伝いさん／", "Helper Lady" },
	{ "関羽・H・雲長／", "Guan Yu H. Yunchang" },
	{ "魔法兵／", "Magic Soldier" },
	{ "街の男／", "Man of the Town" },
	{ "ワシントン花畑／", "Washington Flower Field" },
	{ "案内ロボット／", "Guide Robot" },
	{ "衛星兵器／", "Satellite Weapon" },
	{ "まじょ／", "Witch" },
	{ "かいぞうにんげん／", "Remodeled Human" },
	{ "まほうつかい／", "Mage" },
	{ "鍵付きパケット／", "Locked Packet" },
	{ "女の子達／", "Girls" },
	{ "メイドさん／", "Maid" },
	{ "いやらしい顔の山賊／", "Lecherous-Faced Bandit" },
	{ "老兵／", "Veteran Soldier" },
	{ "金ダライ／", "Gold Basin" },
	{ "左のユキ／", "Yuki (Left)" },
	{ "右のユキ／", "Yuki (Right)" },
	{ "老婆／", "Old Woman" },
	{ "イカ帝国警備兵ホープ／", "Squid Empire Guard Hope" },
	{ "ＪＡＰＡＮ茶屋／", "JAPAN Teahouse" },
	{ "奴隷のおばさん／", "Slave Auntie" },
	{ "上杉軍の女の子／", "Girl of the Uesugi Army" },
	{ "牢屋の中の人／", "Person in the Cell" },
	{ "部隊長／", "Squad Captain" },
	{ "飛行魔物兵エノラゲイ／", "Flying Monster Soldier Enola Gay" },
	{ "ガールズショー会場／", "Girls Show Venue" },
	{ "司祭ズッキ／", "Priest Zukki" },
	{ "神父ミサマム／", "Father Misamamu" },
	{ "主人公は男／", "Protagonist is Male" },
	{ "主人公は女／", "Protagonist is Female" },
	{ "かわぞえ／", "Kawazoe" },
	{ "ポン／", "Pon" },
	{ "てっちゃん／", "Tecchan" },
	{ "中継の樋口さん／", "Broadcaster Higuchi-san" },
	{ "目玉／", "Eyeball" },
	{ "テンプルナイトＢ／", "Temple Knight B" },
	{ "野盗Ａ／", "Bandit A" },
	{ "声Ａ／", "Voice A" },
	{ "住民Ａ／", "Resident A" },
	{ "住民Ｂ／", "Resident B" },
	{ "村人Ｂ／", "Villager B" },
	{ "荷駄隊隊員Ａ／", "Supply Corps Member A" },
	{ "Giant Monster Quelplan", "Giant Monster Quelplan" },
	{ "A lively girl", "A lively girl" },
	{ "Believer Anyu", "Believer Anyu" },
	{ "牢番／", "Jailer" },
	{ "DX会員／", "DX Club Member" },
	{ "運び屋／", "Courier" },
	{ "従者／", "Attendant" },
	{ "新兵／", "New Recruit" },
	{ "モレノル老人／", "Old Man Morenor" },
	{ "天界／", "Heavenly Realm" },
	{ "ごろつき／", "Thug" },
	{ "着ぐるみ／", "Mascot Costume" },
	{ "チューリップ／", "Tulip" },
	{ "氷軍隊長／", "Ice Army Captain" },
	{ "捕らわれた女性／", "Captured Woman" },
	{ "魔物の声／", "Voice of the Monster" },
	{ "闇魔法／", "Dark Magic" },
	{ "スリの少年／", "Pickpocket Boy" },
	{ "伊東・H・甲子太郎／", "Ito H. Kishitarou" },
	{ "藤堂・H・平助／", "Toudou H. Heisuke" },
	{ "システム／", "System" },
	{ "起動したロボット／", "Activated Robot" },
	{ "プレッシャー／", "Pressure" },
	{ "マジスコ／", "Majisuko" },
	{ "若者／", "Young Man" },
	{ "奴隷の娘／", "Slave Girl" },
	{ "神父／", "Father (Priest)" },
	{ "山賊の副頭領／", "Bandit Vice-Boss" },
	{ "受付／", "Receptionist" },
	{ "異界の人間／", "Person from the Otherworld" },
	{ "バーニング・Ｂ／", "Burning B" },
	{ "声Ｂ／", "Voice B" },
	{ "住民Ｃ／", "Resident C" },
	{ "司令部要員Ａ／", "HQ Staff A" },
	{ "住民D／", "Resident D" },
	{ "通行人Ａ／", "Passerby A" },
	{ "通行人Ｂ／", "Passerby B" },
	{ "ハーレムの女の子Ｃ／", "Harem Girl C" },
	{ "老兵Ｂ／", "Veteran Soldier B" },
	{ "老兵Ｃ／", "Veteran Soldier C" },
	{ "村人Ｃ／", "Villager C" },
	{ "不良Ａ／", "Delinquent A" },
	{ "ポピンズの村／", "Poppins Village" },
	{ "Monster Soldiers", "Monster Soldiers" },
	{ "Mysterious Voice", "Mysterious Voice" },
	{ "Historian", "Historian" },
	{ "Female passerby", "Female passerby" },
	{ "Merchant B", "Merchant B" },
	{ "A friend of a fan of Reset", "A friend of a fan of Reset" },
	{ "Shangri-La Security Guard", "Shangri-La Security Guard" },
	{ "Aegis subordinate.", "Aegis subordinate." },
	{ "Soldiers.", "Soldiers." },
	{ "赤兵たち／", "Red Soldiers" },
	{ "腕自慢の武士／", "Boastful Samurai" },
	{ "雇われ兵／", "Hired Soldier" },
	{ "JAPAN武将小比企／", "JAPAN General Kohiki" },
	{ "丸い何か／", "Something Round" },
	{ "大隊長／", "Battalion Captain" },
	{ "魔物兵エノラゲイ／", "Monster Soldier Enola Gay" },
	{ "アスタコプロト／", "Asutakoputo" },
	{ "男ポピンズ／", "Poppins (Male)" },
	{ "女性参謀／", "Female Strategist" },
	{ "男性参謀／", "Male Strategist" },
	{ "輸送隊長／", "Transport Captain" },
	{ "野盗の頭／", "Bandit Boss" },
	{ "野盗／", "Bandit" },
	{ "死を告げる天使／", "Angel of Death" },
	{ "仕事が増えた天使／", "Angel with More Work" },
	{ "迷子／", "Lost Child" },
	{ "御者／", "Coachman" },
	{ "炎軍兵士／", "Flame Army Soldier" },
	{ "炎軍魔法兵／", "Flame Army Mage" },
	{ "氷軍魔法兵／", "Ice Army Mage" },
	{ "魔物兵たち／", "Monster Soldiers" },
	{ "石から戻った兵士／", "Soldier Restored from Stone" },
	{ "石像だった人／", "Person Who Was a Statue" },
	{ "石になっていた人／", "Person Turned to Stone" },
	{ "像になっていた人／", "Person Turned into a Statue" },
	{ "石化されていた人／", "Person Who Had Been Petrified" },
	{ "石像／", "Stone Statue" },
	{ "石像になっていた人／", "Person Who Had Turned into a Statue" },
	{ "女の声／", "A Womans Voice" },
	{ "奴隷娘／", "Slave Girl" },
	{ "にんじゃ／", "Ninja" },
	{ "どれい／", "Slave" },
	{ "ほうおう／", "Phoenix" },
	{ "からー／", "Kalar" },
	{ "むすめ／", "Girl" },
	{ "毒やん／", "Poison Yan" },
	{ "城門／", "Castle Gate" },
	{ "朝日（ＫＤの声）／", "Morning Sun (KDs Voice)" },
	{ "ラルカット／", "Rarukatto" },
	{ "小十郎／", "Kojuurou" },
	{ "大工の棟梁／", "Master Carpenter" },
	{ "警官／", "Police Officer" },
	{ "エンジニア／", "Engineer" },
	{ "要人達／", "VIPs" },
	{ "最凶魔法使いコンビ／", "The Most Evil Mage Duo" },
	{ "奴隷達／", "Slaves" },
	{ "大勢の心の声／", "Many Inner Voices" },
	{ "ダブル奴隷／", "Double Slave" },
	{ "村人／", "Villager" },
	{ "サカナク・テンカ／", "Sakanaku Tenka" },
	{ "ジブル・マクトミ／", "Jiburu Makutomi" },
	{ "魔物たち／", "Monsters" },
	{ "黄色いトリ／", "Yellow Bird" },
	{ "信者／", "Believer" },
	{ "ゴロツキ／", "Thug" },
	{ "村人の男性／", "Villager (Man)" },
	{ "村人の女性／", "Villager (Woman)" },
	{ "諭吉／", "Yukichi" },
	{ "親友長田君／", "Best Friend Nagata-kun" },
	{ "親友志津香／", "Best Friend Shizuka" },
	{ "親友ウズメ／", "Best Friend Uzume" },
	{ "親友乱義／", "Best Friend Rangi" },
	{ "親友ミックス／", "Best Friend Mix" },
	{ "親友スシヌ／", "Best Friend Sushinu" },
	{ "親友元就／", "Best Friend Motonari" },
	{ "親友レリコフ／", "Best Friend Lelikov" },
	{ "親友ドッスワッス／", "Best Friend Doss Wass" },
	{ "親友松下姫／", "Best Friend Princess Matsushita" },
	{ "魔物隊長Ａ／", "Monster Captain A" },
	{ "魔物隊長Ｂ／", "Monster Captain B" },
	{ "五軍兵士Ａ／", "5th Army Soldier A" },
	{ "五軍兵士Ｂ／", "5th Army Soldier B" },
	{ "野盗Ｂ／", "Bandit B" },
	{ "武士Ａ／", "Samurai A" },
	{ "市民Ｃ／", "Citizen C" },
	{ "市民Ａ／", "Citizen A" },
	{ "住民Ｄ／", "Resident D" },
	{ "伝令兵Ｂ／", "Messenger Soldier B" },
	{ "司令部要員Ｂ／", "HQ Staff B" },
	{ "男性A／", "Man A" },
	{ "奴隷娘Ｂ／", "Slave Girl B" },
	{ "リターンデーモンＡ／", "Return Demon A" },
	{ "リターンデーモンＢ／", "Return Demon B" },
	{ "リターンデーモンＣ／", "Return Demon C" },
	{ "通信兵Ａ／", "Signal Soldier A" },
	{ "通信兵Ｂ／", "Signal Soldier B" },
	{ "守備兵Ａ／", "Defense Soldier A" },
	{ "守備兵Ｂ／", "Defense Soldier B" },
	{ "起こされた魔物兵Ａ／", "Awakened Monster Soldier A" },
	{ "起こされた魔物兵Ｂ／", "Awakened Monster Soldier B" },
	{ "ハーレムの女の子Ａ／", "Harem Girl A" },
	{ "ハーレムの女の子Ｂ／", "Harem Girl B" },
	{ "ハーレムの女の子Ｄ／", "Harem Girl D" },
	{ "ハーレムの女の子Ｅ／", "Harem Girl E" },
	{ "山賊Ｄ／", "Bandit D" },
	{ "老兵Ａ／", "Veteran Soldier A" },
	{ "赤鬼Ａ／", "Red Ogre A" },
	{ "青鬼Ａ／", "Blue Ogre A" },
	{ "赤鬼Ｂ／", "Red Ogre B" },
	{ "青鬼Ｂ／", "Blue Ogre B" },
	{ "荷駄隊隊員Ｂ／", "Supply Corps Member B" },
	{ "荷駄隊隊員Ｃ／", "Supply Corps Member C" },
	{ "ミスターＸ／", "Mister X" },
	{ "通行人の女Ａ／", "Passerby Woman A" },
	{ "眼鏡職人　菅原／", "Glasses Craftsman Sugawara" },
	{ "Reset", "Reset" },
	{ "モンスター？／", "Monster?" },
	{ "傭兵隊長／", "Mercenary Captain" },
	{ "ＣＩＴＹ／", "CITY" },
	{ "野良わんわん/", "Stray Dog" },
};